### ISSUE TITLE
Custom tab intents issue 

### ISSUE THREAD

**Issue by J-khatri** [bromite/bromite#1047]
### Bromite version

Version: `90.0.4430.59`
 `arm64`
Android version: (example: `Android 9`)
Device model: (example: `oneplus 6`)

### Flags

These are the flags changed under `chrome://flags`:

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Allow ads for the site; is the bug caused by the adblocker?
No

### Describe the bug

If allow custom tab intents is enabled .. browser crashes if try to open any link received in msg or mail 

If custom tab intents is disabled ... everything works fine 

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to '...settings'
2. Click on 'privacy and security'
3. Scroll down to 'allow custom tab intents' and enable it 
4. Load any links from msg or mail or telegram etc...

### Expected behavior

It should open link normally

**Comment by frankjrp** [comment]
@J-khatri for me it's working fine with `allow custom tab intents` enabled.

I've tested with Gmail and Telegram.

Device: Samsung Galaxy S8 (SM-G950FD)
Android: 9

** Maybe you have some other flag enabled that's causing conflict with the custom tab intents.

**Comment by J-khatri** [comment]
I've only disabled "color gamut" in flags 

I don't think it has anything to do with the custom tab intents 

Not sure though

**Comment by csagan5** [comment]
@J-khatri you did not mention any changed flags in the issue though.

**Comment by J-khatri** [comment]
I think it's  not needed , I've changed that flag after reporting that but... And there is no any relation if it's enabled or disabled ( color gamut )

**Comment by uazo** [comment]
I can't reproduce this problem.. again automatic extraction of logs would be useful...
@J-khatri are you able to send us the logs? 
do you have a rooted phone?

**Comment by J-khatri** [comment]
> I can't reproduce this problem.. again automatic extraction of logs would be useful...
> @J-khatri are you able to send us the logs? 
> do you have a rooted phone?
> 
> 

No ..I'm not rooted

**Comment by 534n0** [comment]
I can confirm this bug too and I'm not altering any flags. It works just fine before.

Version: 90.0.4430.59
arm64
Android version: Android 9
Device model: Xiaomi Redmi Note 7

**Comment by douchesfeedboard** [comment]
Crashing with custom tabs...could it be related to the issue https://github.com/bromite/bromite/issues/1051 ?
Does people who can reproduce this bug use the always incognito mode?

**Comment by 534n0** [comment]
It may be it? But yes, I'm using always incognito mode.

**Comment by jplitza** [comment]
Same issue here, with always incognito mode on.

**Comment by csagan5** [comment]
Fixed in `90.0.4430.74`.

**Comment by 534n0** [comment]
The issue still persists at my device with the latest version (90.0.4430.74)

Here's the log
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'xiaomi/lavender/lavender:9/PKQ1.180904.001/V11.0.6.0.PFGMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 9432, tid: 9432, name: bromite.bromite  >>> org.bromite.bromite <<<
signal 5 (SIGTRAP), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:jni_android.cc(306)] Please include Java exception stack in crash report
'
    x0  0000000000000000  x1  0000007323131c72  x2  00000073ccc1d3c0  x3  0000000000000000
    x4  8080808080808080  x5  fefefefefefefeff  x6  fefefefefefefeff  x7  7f7f7f7f7f7f7f7f
    x8  0000000000000000  x9  0000000000000000  x10 0000000000000001  x11 0000000000000000
    x12 00000000ffffff80  x13 ffffffffffffffff  x14 ffffffffff000000  x15 ffffffffffffffff
    x16 00000073290d8c10  x17 00000073ccb9d3bc  x18 0000000000000010  x19 0000007ffe4e4278
    x20 0000007ffe4e4288  x21 000000000000004f  x22 00000073ccc1d3c0  x23 00000073290eb000
    x24 00000073290eb000  x25 000000732916a028  x26 00000073d1ec75e0  x27 0000007ffe4e3dc8
    x28 0000000000000000  x29 0000007ffe4e4210
    sp  0000007ffe4e3dc0  lr  00000073261eb5bc  pc  00000073261eb70c

backtrace:
    #00 pc 000000000339170c  /data/app/org.bromite.bromite-nsURWrHZ6OSXxLTE9DSr3A==/base.apk (offset 0xe1c000)
    #01 pc 00000000034155e8  /data/app/org.bromite.bromite-nsURWrHZ6OSXxLTE9DSr3A==/base.apk (offset 0xe1c000)
    #02 pc 0000000001d7855c  /data/app/org.bromite.bromite-nsURWrHZ6OSXxLTE9DSr3A==/base.apk (offset 0xe1c000)
    #03 pc 000000000341d7c0  /data/app/org.bromite.bromite-nsURWrHZ6OSXxLTE9DSr3A==/base.apk (offset 0xe1c000)
    #04 pc 000000000341d690  /data/app/org.bromite.bromite-nsURWrHZ6OSXxLTE9DSr3A==/base.apk (offset 0xe1c000)
    #05 pc 000000000341d89c  /data/app/org.bromite.bromite-nsURWrHZ6OSXxLTE9DSr3A==/base.apk (offset 0xe1c000)
    #06 pc 00000000033c871c  /data/app/org.bromite.bromite-nsURWrHZ6OSXxLTE9DSr3A==/base.apk (offset 0xe1c000)
    #07 pc 00000000033d8934  /data/app/org.bromite.bromite-nsURWrHZ6OSXxLTE9DSr3A==/base.apk (offset 0xe1c000)
    #08 pc 000000000340b6b4  /data/app/org.bromite.bromite-nsURWrHZ6OSXxLTE9DSr3A==/base.apk (offset 0xe1c000)
    #09 pc 000000000340b66c  /data/app/org.bromite.bromite-nsURWrHZ6OSXxLTE9DSr3A==/base.apk (offset 0xe1c000)
    #10 pc 000000000340b378  /data/app/org.bromite.bromite-nsURWrHZ6OSXxLTE9DSr3A==/base.apk (offset 0xe1c000)
    #11 pc 0000000000014ff8  /system/lib64/libutils.so (android::Looper::pollInner(int)+836)
    #12 pc 0000000000014c18  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+60)
    #13 pc 0000000000127dbc  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
    #14 pc 0000000000df814c  /system/framework/arm64/boot-framework.oat (offset 0xa44000) (android.media.MediaExtractor.seekTo [DEDUPED]+140)
    #15 pc 00000000017aeda0  /system/framework/arm64/boot-framework.oat (offset 0xa44000) (android.os.MessageQueue.next+240)
    #16 pc 0000000001f86f1c  /system/framework/arm64/boot-framework.oat (offset 0xa44000) (android.os.Looper.loop+636)
    #17 pc 0000000000f30af8  /system/framework/arm64/boot-framework.oat (offset 0xa44000) (android.app.ActivityThread.main+664)
    #18 pc 000000000055764c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
    #19 pc 00000000000cfce8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
    #20 pc 000000000045dd7c  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
    #21 pc 000000000045f7d0  /system/lib64/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1440)
    #22 pc 00000000003ef398  /system/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52)
    #23 pc 000000000078eed4  /system/framework/arm64/boot-core-oj.oat (offset 0x2dc000) (java.lang.Class.getDeclaredMethodInternal [DEDUPED]+180)
    #24 pc 0000000002486438  /system/framework/arm64/boot-framework.oat (offset 0xa44000) (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+136)
    #25 pc 00000000024927d8  /system/framework/arm64/boot-framework.oat (offset 0xa44000) (com.android.internal.os.ZygoteInit.main+2104)
    #26 pc 000000000055764c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
    #27 pc 00000000000cfce8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
    #28 pc 000000000045dd7c  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
    #29 pc 000000000045d9dc  /system/lib64/libart.so (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+424)
    #30 pc 0000000000362cd8  /system/lib64/libart.so (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+652)
    #31 pc 00000000000b2b74  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+116)
    #32 pc 00000000000b5710  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+924)
    #33 pc 0000000000002528  /system/bin/app_process64 (main+2012)
    #34 pc 00000000000c9270  /system/lib64/libc.so (__libc_init+88)
```

**Comment by uazo** [comment]
> Abort message: '[FATAL:jni_android.cc(306)] Please include Java exception stack in crash report

can you include the stacktrace? a few lines above normally

**Comment by csagan5** [comment]
The crash of @534n0 does not seem in Bromite:
```
Stack Trace:
  RELADDR   FUNCTION                                                                          FILE:LINE
  v------>  logging::LogMessage::~LogMessage()::$_2::operator()() const                       ../../base/logging.cc:886:7
  000000000339170c  logging::LogMessage::~LogMessage()                                                ../../base/logging.cc:886:7
  00000000034155e8  base::android::CheckException(_JNIEnv*)                                           ../../base/android/jni_android.cc:306:3
  v------>  jni_generator::CheckException(_JNIEnv*)                                           ../../base/android/jni_generator/jni_generator_helper.h:52:3
  0000000001d7855c  jni_generator::JniJavaCallContextChecked::~JniJavaCallContextChecked()            ../../base/android/jni_generator/jni_generator_helper.h:117:5
  000000000341d7c0  JNI_Runnable::Java_Runnable_run(_JNIEnv*, base::android::JavaRef<_jobject*> const&)  gen/base/android_runtime_jni_headers/Runnable_jni.h:60:1
  000000000341d690  base::PostTaskAndroid::RunJavaTask(base::android::ScopedJavaGlobalRef<_jobject*>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)  ../../base/android/task_scheduler/post_task_android.cc:96:3
  v------>  void base::internal::FunctorTraits<void (*)(base::android::ScopedJavaGlobalRef<_jobject*>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&), void>::Invoke<void (*)(base::android::ScopedJavaGlobalRef<_jobject*>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&), base::android::ScopedJavaGlobalRef<_jobject*>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(void (*&&)(base::android::ScopedJavaGlobalRef<_jobject*>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&), base::android::ScopedJavaGlobalRef<_jobject*>&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&)  ../../base/bind_internal.h:393:12
  v------>  void base::internal::InvokeHelper<false, void>::MakeItSo<void (*)(base::android::ScopedJavaGlobalRef<_jobject*>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&), base::android::ScopedJavaGlobalRef<_jobject*>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(void (*&&)(base::android::ScopedJavaGlobalRef<_jobject*>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&), base::android::ScopedJavaGlobalRef<_jobject*>&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&)  ../../base/bind_internal.h:637:12
  v------>  void base::internal::Invoker<base::internal::BindState<void (*)(base::android::ScopedJavaGlobalRef<_jobject*>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&), base::android::ScopedJavaGlobalRef<_jobject*>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, void ()>::RunImpl<void (*)(base::android::ScopedJavaGlobalRef<_jobject*>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&), std::__1::tuple<base::android::ScopedJavaGlobalRef<_jobject*>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, 0ul, 1ul>(void (*&&)(base::android::ScopedJavaGlobalRef<_jobject*>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&), std::__1::tuple<base::android::ScopedJavaGlobalRef<_jobject*>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&&, std::__1::integer_sequence<unsigned long, 0ul, 1ul>)  ../../base/bind_internal.h:710:12
  000000000341d89c  base::internal::Invoker<base::internal::BindState<void (*)(base::android::ScopedJavaGlobalRef<_jobject*>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&), base::android::ScopedJavaGlobalRef<_jobject*>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, void ()>::RunOnce(base::internal::BindStateBase*)  ../../base/bind_internal.h:679:12
  v------>  base::OnceCallback<void ()>::Run() &&                                             ../../base/callback.h:101:12
  00000000033c871c  $d.24                                                                             ../../base/task/common/task_annotator.cc:163:33
  v------>  base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow*)  ../../base/task/sequence_manager/thread_controller_with_message_pump_impl.cc:351:25
  00000000033d8934  base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()   ../../base/task/sequence_manager/thread_controller_with_message_pump_impl.cc:264:36
  000000000340b6b4  base::MessagePumpForUI::DoNonDelayedLooperWork(bool)                              ../../base/message_loop/message_pump_android.cc:217:33
  000000000340b66c  base::MessagePumpForUI::OnNonDelayedLooperCallback()                              ../../base/message_loop/message_pump_android.cc:203:3
  000000000340b378  base::(anonymous namespace)::NonDelayedLooperCallback(int, int, void*)            ../../base/message_loop/message_pump_android.cc:71:9
  0000000000014ff8  android::Looper::pollInner(int)+836                                               /system/lib64/libutils.so
  0000000000014c18  android::Looper::pollOnce(int, int*, int*, void**)+60                             /system/lib64/libutils.so
  0000000000127dbc  android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44  /system/lib64/libandroid_runtime.so
  0000000000df814c  offset 0xa44000) (android.media.MediaExtractor.seekTo [DEDUPED]+140               /system/framework/arm64/boot-framework.oat
  00000000017aeda0  offset 0xa44000) (android.os.MessageQueue.next+240                                /system/framework/arm64/boot-framework.oat
  0000000001f86f1c  offset 0xa44000) (android.os.Looper.loop+636                                      /system/framework/arm64/boot-framework.oat
  0000000000f30af8  offset 0xa44000) (android.app.ActivityThread.main+664                             /system/framework/arm64/boot-framework.oat
  000000000055764c  art_quick_invoke_static_stub+604                                                  /system/lib64/libart.so
  00000000000cfce8  art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232  /system/lib64/libart.so
  000000000045dd7c  art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104  /system/lib64/libart.so
  000000000045f7d0  art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1440  /system/lib64/libart.so
  00000000003ef398  art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52             /system/lib64/libart.so
  000000000078eed4  offset 0x2dc000) (java.lang.Class.getDeclaredMethodInternal [DEDUPED]+180         /system/framework/arm64/boot-core-oj.oat
  0000000002486438  offset 0xa44000) (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+136  /system/framework/arm64/boot-framework.oat
  00000000024927d8  offset 0xa44000) (com.android.internal.os.ZygoteInit.main+2104                    /system/framework/arm64/boot-framework.oat
  000000000055764c  art_quick_invoke_static_stub+604                                                  /system/lib64/libart.so
  00000000000cfce8  art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232  /system/lib64/libart.so
  000000000045dd7c  art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104  /system/lib64/libart.so
  000000000045d9dc  art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+424  /system/lib64/libart.so
  0000000000362cd8  art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+652  /system/lib64/libart.so
  00000000000b2b74  _JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+116                     /system/lib64/libandroid_runtime.so
  00000000000b5710  android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+924  /system/lib64/libandroid_runtime.so
  0000000000002528  main+2012                                                                         /system/bin/app_process64
  00000000000c9270  __libc_init+88                                                                    /system/lib64/libc.so
```

Maybe with the Java stacktrace we can check better.

**Comment by csagan5** [comment]
@uazo it should be possible to reproduce it with the AVD emulator already?

**Comment by uazo** [comment]
> does not seem in Bromite:

that is the java vm native stacktrace, it is normal to be reported in log.
it is in the log because the crash is probably in a `@CalledByNative` method

> it should be possible to reproduce it with the AVD emulator already?

i can't reproduce it, maybe can someone give us more details on what happens?

**Comment by csagan5** [comment]
If we cannot reproduce it we are not going to blindly make changes anyways.

**Comment by 534n0** [comment]
Sorry @csagan5 @uazo for a very late reply, my phone wasn't rooted. So I try find a way to unlock it and root so I can provide a better log. Here's a more complete log.

https://github.com/bromite/bromite/files/6330033/2021-04-18-03-09-54.txt

**Comment by csagan5** [comment]
@534n0 you do not need root to get the logs with `adb logcat`.

**Comment by csagan5** [comment]
@uazo this does not seem a crash in the browser but on the Android media stack

**Comment by 534n0** [comment]
Good news @csagan5 @uazo, I've managed to solve this issue by enabling "Chrome Custom Tabs Incognito mode" flag. Thanks.

**Comment by 534n0** [comment]
Not entirely a good news, just realized the bug still there if Bromite isn't running in the background. But when Bromite already running, it works fine when enabling the "Chrome Custom Tabs Incognito mode" flag.

**Comment by uazo** [comment]
>  does not seem a crash in the browser but on the Android media stack

I see this problem:

```
04-18 03:09:45.227 W/System.err(27057): java.lang.IllegalStateException: Attempting to open tab in wrong model
04-18 03:09:45.227 W/System.err(27057): 	at Bl1.l(chromium-ChromePublic.apk-stable-1618345740:25)
04-18 03:09:45.227 W/System.err(27057): 	at vI.j(chromium-ChromePublic.apk-stable-1618345740:37)
04-18 03:09:45.227 W/System.err(27057): 	at uk.r(chromium-ChromePublic.apk-stable-1618345740:8)
04-18 03:09:45.227 W/System.err(27057): 	at org.chromium.chrome.browser.customtabs.CustomTabActivity.r(chromium-ChromePublic.apk-stable-1618345740:6)
04-18 03:09:45.227 W/System.err(27057): 	at vf.E(chromium-ChromePublic.apk-stable-1618345740:1)
04-18 03:09:45.227 W/System.err(27057): 	at yw.run(chromium-ChromePublic.apk-stable-1618345740:2)
04-18 03:09:45.227 W/System.err(27057): 	at zs.run(chromium-ChromePublic.apk-stable-1618345740:10)
04-18 03:09:45.227 W/System.err(27057): 	at android.os.MessageQueue.nativePollOnce(Native Method)
04-18 03:09:45.227 W/System.err(27057): 	at android.os.MessageQueue.next(MessageQueue.java:326)
04-18 03:09:45.227 W/System.err(27057): 	at android.os.Looper.loop(Looper.java:165)
04-18 03:09:45.227 W/System.err(27057): 	at android.app.ActivityThread.main(ActivityThread.java:6810)
04-18 03:09:45.227 W/System.err(27057): 	at java.lang.reflect.Method.invoke(Native Method)
04-18 03:09:45.227 W/System.err(27057): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
04-18 03:09:45.227 W/System.err(27057): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
04-18 03:09:45.229 F/chromium(27057): [FATAL:jni_android.cc(306)] Please include Java exception stack in crash report
```

@csagan5  can you deobfuscate that log?

I see this too:
```
04-18 03:09:46.016 W/System.err(20909): java.net.URISyntaxException: Illegal character in authority at index 7: http://*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-18 03:09:46.016 W/System.err(20909): pid: 21109, tid: 21109, name: bromite.bromite  >>> org.bromite.bromite <<<
04-18 03:09:46.016 W/System.err(20909): signal 5 (SIGTRAP), code -6 (SI_TKILL), fault addr --------
04-18 03:09:46.016 W/System.err(20909): Abort message: '[FATAL:jni_android.cc(306)] Please include Java exception stack in crash report
...
04-18 03:09:46.017 W/System.err(20909): 	at me.ccrama.redditslide.ContentType.getContentType(ContentType.java:168)
04-18 03:09:46.017 W/System.err(20909): 	at me.ccrama.redditslide.Activities.MainActivity.checkClipboard(MainActivity.java:1318)
04-18 03:09:46.017 W/System.err(20909): 	at me.ccrama.redditslide.Activities.MainActivity.onResume(MainActivity.java:1350)
```

what is inside `http://*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***` ? and is me.ccrama.redditslide maybe https://github.com/ccrama/Slide ?

another thing: the flag "Chrome Custom Tabs Incognito mode" does not work for me, can you confirm it? you can try with  
```
adb shell am start -a android.intent.action.VIEW -d http://www.stackoverflow.com --es android.support.customtabs.extra.SESSION "1"
```

**Comment by 534n0** [comment]
@uazo yes correct, that's Slide for Reddit. The crash is not just happening there, it's just an apps that I quickly choose to reproduce the crash. Any other apps can cause the crash too.

> Not entirely a good news, just realized the bug still there if Bromite isn't running in the background. But when Bromite already running, it works fine when enabling the "Chrome Custom Tabs Incognito mode" flag.

I want to add what I mean by "running in the background", it must be visible at the recent apps display. Even when I set it to autorun and not optimized by battery saver, it will crash too. It must specifically visible in recent apps.

**Comment by csagan5** [comment]
> @csagan5 can you deobfuscate that log?

It does not work. Which Bromite version is this from? Perhaps more text is missing?

I will look into releasing the symbols on next release.

**Comment by 534n0** [comment]
Thanks for the hardwork @uazo @csagan5, I don't encounter this bug anymore with the latest release (90.0.4430.204)

**Comment by csagan5** [comment]
I will close this for now. @uazo if you can reproduce this with latest version we can re-open it.
