### ISSUE TITLE
App crashes when I started download any file

### ISSUE THREAD

**Issue by ygz213** [bromite/bromite#1184]
### Bromite version

Version: `91.0.4472.50`
Arch: `arm`
Android version: `5.0.1`
Device model: `TCL-8079`

### Flags

These are the flags changed under `chrome://flags`:

`#disable-webgl` / WebGL : Disabled
`#smooth-scrolling` / Smooth Scrolling : Enabled
`#enable-quic` / Experimental QUIC protocol : Enabled
`#read-later` / Reading List : Enabled
`#enable-ephemeral-tab-bottom-sheet` / An ephemeral Preview Tab using the bottom sheet : Enabled

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is this bug happening in an incognito tab?

In an incognito and normal tab

### Allow ads for the site; is the bug caused by the adblocker?

No

### Is the bug a crash?

Yes

### Describe the bug

App crashes when I started download any file and it don't continue to download. A few seconds after opening the app, "Downloading file..." appears at the bottom and crashes again.

### Steps to reproduce the bug

1. Go to any download link
2. Click on 'download'
3. See crash

### Expected behavior

App must not to crash.

**Comment by ygz213** [comment]
The crash also happened after I reset the app's data.

**Comment by csagan5** [comment]
Fixed in `91.0.4472.97`.

**Comment by ygz213** [comment]
Issue isn't fixed. The app is still crashing after started download but it don't crashing a few seconds after opening the app. I can record a video if you want.

**Comment by ygz213** [comment]
@csagan5 Please reopen this issue.

**Comment by csagan5** [comment]
@ygz213 please paste the crash log, you can find it with `adb logcat`

**Comment by ygz213** [comment]
I don't know debugging.

**Comment by ygz213** [comment]
I started adb logcat just before the download started and I stopped after the crash. logcat.txt happened 74555 lines. I don't know if this is normal. Should I really paste? (74555 lines)

**Comment by csagan5** [comment]
@ygz213 only the last couple hundred lines will suffice

**Comment by ygz213** [comment]
```
I/SurfaceFlinger(  141): [Built-in Screen (type:0)] fps:0.296979,dur:6734.49,max:6716.23,min:18.26

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/ANRManager(  548): updateProcessStats

E/WifiStateMachine(  548):  ConnectedState (when=-3ms what=131155 arg1=36!CMD_RSSI_POLL 36 0 "FiberHGW_ZT5F53_2.4GHz" 24:58:6e:95:2d:78 rssi=-58 f=2447 sc=60 link=65 tx=167,6, 0,0, 0,0  rx=277,5 bcn=0 [on:0 tx:0 rx:0 period:3000] from screen [on:0 period:-442066866] gl hn u24 rssi=-53 ag=0 hr ticks 4,140,637 ls-=0 [56,56,60,60,65] brc=0 lrc=0

E/WifiStateMachine(  548):  L2ConnectedState (when=-5ms what=131155 arg1=36!CMD_RSSI_POLL 36 0 "FiberHGW_ZT5F53_2.4GHz" 24:58:6e:95:2d:78 rssi=-58 f=2447 sc=60 link=65 tx=167,6, 0,0, 0,0  rx=277,5 bcn=0 [on:0 tx:0 rx:0 period:1] from screen [on:0 period:-442066865] gl hn u24 rssi=-53 ag=0 hr ticks 4,140,637 ls-=0 [56,56,60,60,65] brc=0 lrc=0

E/WifiStateMachine(  548):  get link layer stats 0

D/WifiHW  (  548): enter -->wifi_send_command cmd=IFNAME=wlan0 SIGNAL_POLL

D/wpa_supplicant(  969): wlan0: Control interface command 'SIGNAL_POLL'

I/WifiStateMachine(  548): fetchRssiLinkSpeedAndFrequencyNative, newRssi:-58, newLinkSpeed:65, SSID:"FiberHGW_ZT5F53_2.4GHz"

D/WifiStateMachine(  548): mLastSignalLevel:3, newSignalLevel:3

E/WifiConfigStore(  548): updateConfiguration freq=2447 BSSID=24:58:6e:95:2d:78 RSSI=-57 "FiberHGW_ZT5F53_2.4GHz"WPA_PSK

V/ActivityManager(  548): Broadcast sticky: Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) } ordered=false userid=-1 callerApp=ProcessRecord{24be305c 548:system/1000}

D/WifiWatchdogStateMachine(  548): RSSI current: 3 new: -58, 3

D/StatusBar.NetworkController(  865): onReceive, intent action = android.net.wifi.RSSI_CHANGED

D/StatusBar.NetworkController(  865): updateWifiState: mWifiLevel = 3  mWifiRssi=-58 mWifiConnected is true

D/StatusBar.NetworkController(  865): updateWifiIcons: WifiConnected : inetCondition = 1  mWifiLevel=3 mWifiActivity =3

D/StatusBar.NetworkController(  865): updateWifiActivityIcons: WifiConnected:   mWifiLevel=3 mWifiActivity =3

D/StatusBar.NetworkController(  865): refreshViews connected={ wifi } level=?? combinedSignalIconId=0x7f020193/com.android.systemui:drawable/stat_sys_wifi_signal_3_fully_inout combinedActivityIconId=0x0 mobileLabel= wifiLabel="FiberHGW_ZT5F53_2.4GHz"xxxxXXXXxxxxXXXX emergencyOnly=false combinedLabel="FiberHGW_ZT5F53_2.4GHz"xxxxXXXXxxxxXXXX mAirplaneMode=false mDataActivity=0 mPhoneSignalIconId=0x7f02017c mPhoneSignalIconId2=0x0 mDataDirectionIconId=0x0 mDataSignalIconId=0x0 mDataTypeIconId=0x0 mWifiIconId=0x7f020193 mQSPhoneSignalIconId=0x7f0200b4 mQSDataTypeIconId=0x0 mQSWifiIconId=0x7f0200c4 mBluetoothTetherIconId=0x1080697

D/SignalClusterView(  865): setNetworkType(0), NetworkType=null

D/SignalClusterView(  865): setShowSimIndicator(0), showSimIndicator=false simIndicatorResource = 0

D/SignalClusterView(  865): apply(), mWifiVisible is true

D/SignalClusterView(  865): apply(), slot=0, mMobileVisible=false, mIsAirplaneMode=false

D/SignalClusterView(  865): setNetworkType(0), NetworkType=null

D/SignalClusterView(  865): setShowSimIndicator(0), showSimIndicator=false simIndicatorResource = 0

D/SignalClusterView(  865): apply(), mWifiVisible is true

D/SignalClusterView(  865): apply(), slot=0, mMobileVisible=false, mIsAirplaneMode=false

D/SignalClusterView(  865): setNetworkType(0), NetworkType=null

D/SignalClusterView(  865): setShowSimIndicator(0), showSimIndicator=false simIndicatorResource = 0

D/SignalClusterView(  865): apply(), mWifiVisible is true

D/SignalClusterView(  865): apply(), slot=0, mMobileVisible=false, mIsAirplaneMode=false

E/WifiTrafficPoller(  548): TRAFFIC_STATS_POLL true Token 152 num clients 7

E/WifiTrafficPoller(  548):  packet count Tx=94131 Rx=141629

E/WifiTrafficPoller(  548): notifying of data activity 0

D/StatusBar.NetworkController(  865): updateWifiActivityIcons: WifiConnected:   mWifiLevel=3 mWifiActivity =0

D/StatusBar.NetworkController(  865): refreshViews connected={ wifi } level=?? combinedSignalIconId=0x7f020191/com.android.systemui:drawable/stat_sys_wifi_signal_3_fully combinedActivityIconId=0x0 mobileLabel= wifiLabel="FiberHGW_ZT5F53_2.4GHz"xxxxXXXXxxxxXXXX emergencyOnly=false combinedLabel="FiberHGW_ZT5F53_2.4GHz"xxxxXXXXxxxxXXXX mAirplaneMode=false mDataActivity=0 mPhoneSignalIconId=0x7f02017c mPhoneSignalIconId2=0x0 mDataDirectionIconId=0x0 mDataSignalIconId=0x0 mDataTypeIconId=0x0 mWifiIconId=0x7f020191 mQSPhoneSignalIconId=0x7f0200b4 mQSDataTypeIconId=0x0 mQSWifiIconId=0x7f0200c4 mBluetoothTetherIconId=0x1080697

D/StatusBar.NetworkController(  865): refreshViews(0), set parameters to signal cluster view.

D/SignalClusterView(  865): setWifiIndicators, visible=true, strengthIcon=2130837905, contentDescription=Kablosuz sinyali üç çubuk.

D/SignalClusterView(  865): setMobileDataIndicators(0), visible=false, strengthIcon[0] ~ [1] 2130837884 ~ 0, mMobileTypeId: 0, isTypeIconWide: false

D/SignalClusterView(  865): setIsAirplaneMode=false airplaneIconId:0

D/SignalClusterView(  865): setWifiIndicators, visible=true, strengthIcon=2130837905, contentDescription=Kablosuz sinyali üç çubuk.

D/SignalClusterView(  865): setMobileDataIndicators(0), visible=false, strengthIcon[0] ~ [1] 2130837884 ~ 0, mMobileTypeId: 0, isTypeIconWide: false

D/SignalClusterView(  865): setIsAirplaneMode=false airplaneIconId:0

D/SignalClusterView(  865): setWifiIndicators, visible=true, strengthIcon=2130837905, contentDescription=Kablosuz sinyali üç çubuk.

D/SignalClusterView(  865): setMobileDataIndicators(0), visible=false, strengthIcon[0] ~ [1] 2130837884 ~ 0, mMobileTypeId: 0, isTypeIconWide: false

D/SignalClusterView(  865): setIsAirplaneMode=false airplaneIconId:0

D/SignalClusterView(  865): setNetworkType(0), NetworkType=null

D/SignalClusterView(  865): setShowSimIndicator(0), showSimIndicator=false simIndicatorResource = 0

D/SignalClusterView(  865): apply(), mWifiVisible is true

D/SignalClusterView(  865): apply(), slot=0, mMobileVisible=false, mIsAirplaneMode=false

D/SignalClusterView(  865): setNetworkType(0), NetworkType=null

D/SignalClusterView(  865): setShowSimIndicator(0), showSimIndicator=false simIndicatorResource = 0

D/SignalClusterView(  865): apply(), mWifiVisible is true

D/SignalClusterView(  865): apply(), slot=0, mMobileVisible=false, mIsAirplaneMode=false

D/SignalClusterView(  865): setNetworkType(0), NetworkType=null

D/SignalClusterView(  865): setShowSimIndicator(0), showSimIndicator=false simIndicatorResource = 0

D/SignalClusterView(  865): apply(), mWifiVisible is true

D/SignalClusterView(  865): apply(), slot=0, mMobileVisible=false, mIsAirplaneMode=false

I/BufferQueueProducer(  141): [StatusBar](this:0xb6333800,id:8,api:1,p:865,c:141) queueBuffer: fps=1.00 dur=1001.00 max=1001.00 min=1001.00

I/SurfaceFlinger(  141): [Built-in Screen (type:0)] fps:0.999245,dur:1000.76,max:1000.76,min:1000.76

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/ANRManager(  548): CPU update time < 2.5sec

I/ANRManager(  548): CPU update time < 2.5sec

I/ANRManager(  548): CPU update time < 2.5sec

I/ANRManager(  548): CPU update time < 2.5sec

E/WifiTrafficPoller(  548): TRAFFIC_STATS_POLL true Token 152 num clients 7

E/WifiTrafficPoller(  548):  packet count Tx=94131 Rx=141629

I/ANRManager(  548): CPU update time < 2.5sec

I/ANRManager(  548): CPU update time < 2.5sec

I/ANRManager(  548): updateProcessStats

I/ANRManager(  548): CPU update time < 2.5sec

I/ANRManager(  548): CPU update time < 2.5sec

I/ANRManager(  548): CPU update time < 2.5sec

E/WifiTrafficPoller(  548): TRAFFIC_STATS_POLL true Token 152 num clients 7

E/WifiTrafficPoller(  548):  packet count Tx=94131 Rx=141629

I/ANRManager(  548): CPU update time < 2.5sec

E/WifiStateMachine(  548):  ConnectedState (when=-4ms what=131155 arg1=36!CMD_RSSI_POLL 36 0 "FiberHGW_ZT5F53_2.4GHz" 24:58:6e:95:2d:78 rssi=-58 f=2447 sc=60 link=65 tx=84,3, 0,0, 0,0  rx=139,2 bcn=0 [on:0 tx:0 rx:0 period:3001] from screen [on:0 period:-442063856] gl hn u24 rssi=-53 ag=0 hr ticks 4,140,637 ls-=0 [56,56,60,60,65] brc=0 lrc=0

E/WifiStateMachine(  548):  L2ConnectedState (when=-6ms what=131155 arg1=36!CMD_RSSI_POLL 36 0 "FiberHGW_ZT5F53_2.4GHz" 24:58:6e:95:2d:78 rssi=-58 f=2447 sc=60 link=65 tx=84,3, 0,0, 0,0  rx=139,2 bcn=0 [on:0 tx:0 rx:0 period:2] from screen [on:0 period:-442063854] gl hn u24 rssi=-53 ag=0 hr ticks 4,140,637 ls-=0 [56,56,60,60,65] brc=0 lrc=0

E/WifiStateMachine(  548):  get link layer stats 0

D/WifiHW  (  548): enter -->wifi_send_command cmd=IFNAME=wlan0 SIGNAL_POLL

D/wpa_supplicant(  969): wlan0: Control interface command 'SIGNAL_POLL'

I/WifiStateMachine(  548): fetchRssiLinkSpeedAndFrequencyNative, newRssi:-57, newLinkSpeed:65, SSID:"FiberHGW_ZT5F53_2.4GHz"

D/WifiStateMachine(  548): mLastSignalLevel:3, newSignalLevel:3

E/WifiConfigStore(  548): updateConfiguration freq=2447 BSSID=24:58:6e:95:2d:78 RSSI=-57 "FiberHGW_ZT5F53_2.4GHz"WPA_PSK

V/ActivityManager(  548): Broadcast sticky: Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) } ordered=false userid=-1 callerApp=ProcessRecord{24be305c 548:system/1000}

D/WifiWatchdogStateMachine(  548): RSSI current: 3 new: -57, 3

D/StatusBar.NetworkController(  865): onReceive, intent action = android.net.wifi.RSSI_CHANGED

D/StatusBar.NetworkController(  865): updateWifiState: mWifiLevel = 3  mWifiRssi=-57 mWifiConnected is true

D/StatusBar.NetworkController(  865): updateWifiIcons: WifiConnected : inetCondition = 1  mWifiLevel=3 mWifiActivity =0

D/StatusBar.NetworkController(  865): updateWifiActivityIcons: WifiConnected:   mWifiLevel=3 mWifiActivity =0

D/StatusBar.NetworkController(  865): refreshViews connected={ wifi } level=?? combinedSignalIconId=0x7f020191/com.android.systemui:drawable/stat_sys_wifi_signal_3_fully combinedActivityIconId=0x0 mobileLabel= wifiLabel="FiberHGW_ZT5F53_2.4GHz"xxxxXXXXxxxxXXXX emergencyOnly=false combinedLabel="FiberHGW_ZT5F53_2.4GHz"xxxxXXXXxxxxXXXX mAirplaneMode=false mDataActivity=0 mPhoneSignalIconId=0x7f02017c mPhoneSignalIconId2=0x0 mDataDirectionIconId=0x0 mDataSignalIconId=0x0 mDataTypeIconId=0x0 mWifiIconId=0x7f020191 mQSPhoneSignalIconId=0x7f0200b4 mQSDataTypeIconId=0x0 mQSWifiIconId=0x7f0200c4 mBluetoothTetherIconId=0x1080697

D/SignalClusterView(  865): setNetworkType(0), NetworkType=null

D/SignalClusterView(  865): setShowSimIndicator(0), showSimIndicator=false simIndicatorResource = 0

D/SignalClusterView(  865): apply(), mWifiVisible is true

D/SignalClusterView(  865): apply(), slot=0, mMobileVisible=false, mIsAirplaneMode=false

D/SignalClusterView(  865): setNetworkType(0), NetworkType=null

D/SignalClusterView(  865): setShowSimIndicator(0), showSimIndicator=false simIndicatorResource = 0

D/SignalClusterView(  865): apply(), mWifiVisible is true

D/SignalClusterView(  865): apply(), slot=0, mMobileVisible=false, mIsAirplaneMode=false

D/SignalClusterView(  865): setNetworkType(0), NetworkType=null

D/SignalClusterView(  865): setShowSimIndicator(0), showSimIndicator=false simIndicatorResource = 0

D/SignalClusterView(  865): apply(), mWifiVisible is true

D/SignalClusterView(  865): apply(), slot=0, mMobileVisible=false, mIsAirplaneMode=false

D/hwcomposer(  141): [DPY] UEventThread::threadLoop poll return 1

I/hwcomposer(  141): [DPY] UEventThread::threadLoop recv change@/devices/platform/battery/power_supply/wireless

D/hwcomposer(  141): [DPY] handle_uevents : s = 0xb4c14090, len = 210

D/hwcomposer(  141): [DPY] UEventThread::threadLoop poll wait

D/hwcomposer(  141): [DPY] UEventThread::threadLoop poll return 1

I/hwcomposer(  141): [DPY] UEventThread::threadLoop recv change@/devices/platform/battery/power_supply/battery

D/hwcomposer(  141): [DPY] handle_uevents : s = 0xb4c14090, len = 729

D/hwcomposer(  141): [DPY] UEventThread::threadLoop poll wait

D/BatteryService(  548): mBatteryVoltage=4109, batteryLevel=50

D/hwcomposer(  141): [DPY] UEventThread::threadLoop poll return 1

I/hwcomposer(  141): [DPY] UEventThread::threadLoop recv change@/devices/platform/battery/power_supply/ac

D/hwcomposer(  141): [DPY] handle_uevents : s = 0xb4c14090, len = 192

D/hwcomposer(  141): [DPY] UEventThread::threadLoop poll wait

V/ActivityManager(  548): Broadcast sticky: Intent { act=android.intent.action.BATTERY_CHANGED flg=0x60000010 (has extras) } ordered=false userid=-1 callerApp=null

D/hwcomposer(  141): [DPY] UEventThread::threadLoop poll return 1

I/hwcomposer(  141): [DPY] UEventThread::threadLoop recv change@/devices/platform/battery/power_supply/usb

D/hwcomposer(  141): [DPY] handle_uevents : s = 0xb4c14090, len = 195

D/PowerManagerService(  548): updateIsPoweredLocked: wasPowered=true, mIsPowered=true, oldPlugType=2, mPlugType=2, mBatteryLevel=74

D/UsbDeviceManager(  548): onReceive - BATTERY_CHANGED - mPlugType: 2, mSettingUsbCharging: false, mConnected: true, mSettingUsbBicr: false

D/WifiService(  548): onReceive, action:android.intent.action.BATTERY_CHANGED

D/hwcomposer(  141): [DPY] UEventThread::threadLoop poll wait

D/WifiController(  548): DeviceActiveState{ when=0 what=155652 arg1=2 target=com.android.internal.util.StateMachine$SmHandler }

D/WifiController(  548): StaEnabledState{ when=-1ms what=155652 arg1=2 target=com.android.internal.util.StateMachine$SmHandler }

D/WifiController(  548): DefaultState{ when=-2ms what=155652 arg1=2 target=com.android.internal.util.StateMachine$SmHandler }

D/WifiController(  548): battery changed pluggedType: 2

D/KeyguardUpdateMonitor(  865): received broadcast android.intent.action.BATTERY_CHANGED

D/KeyguardUpdateMonitor(  865): handleBatteryUpdate index=0 updateInteresting=false

I/BufferQueueProducer(  141): [StatusBar](this:0xb6333800,id:8,api:1,p:865,c:141) queueBuffer: fps=0.44 dur=2275.43 max=2275.43 min=2275.43

I/SurfaceFlinger(  141): [Built-in Screen (type:0)] fps:0.439665,dur:2274.46,max:2274.46,min:2274.46

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/ANRManager(  548): CPU update time < 2.5sec

E/WifiTrafficPoller(  548): TRAFFIC_STATS_POLL true Token 152 num clients 7

E/WifiTrafficPoller(  548):  packet count Tx=94131 Rx=141629

D/ActivityThread( 1331): SVC-UNBIND_SERVICE handled : 0 / BindServiceData{token=android.os.BinderProxy@2880d146 intent=Intent { act=com.google.android.gms.location.reporting.service.START pkg=com.google.android.gms }}

D/ActivityThread( 1331): SVC-Destroying service: com.google.android.location.reporting.service.ReportingAndroidService@2233bd82

D/ActivityThread( 1331): SVC-STOP_SERVICE handled : 0 / android.os.BinderProxy@2880d146
```

**Comment by ygz213** [comment]
Also I guess crash is this:

```
W/System.err( 8134): 	at hh.b(chromium-ChromePublic.apk-stable-1622851880:10)

W/System.err( 8134): 	at ch.b(chromium-ChromePublic.apk-stable-1622851880:3)

W/System.err( 8134): 	at go1.a(chromium-ChromePublic.apk-stable-1622851880:1)

W/System.err( 8134): 	at dh.c(chromium-ChromePublic.apk-stable-1622851880:8)

W/System.err( 8134): 	at org.chromium.chrome.browser.download.service.DownloadTaskScheduler.scheduleTask(chromium-ChromePublic.apk-stable-1622851880:14)

W/System.err( 8134): 	at android.os.MessageQueue.nativePollOnce(Native Method)

W/System.err( 8134): 	at android.os.MessageQueue.next(MessageQueue.java:148)

W/System.err( 8134): 	at android.os.Looper.loop(Looper.java:151)

W/System.err( 8134): 	at android.app.ActivityThread.main(ActivityThread.java:5576)

W/System.err( 8134): 	at java.lang.reflect.Method.invoke(Native Method)

W/System.err( 8134): 	at java.lang.reflect.Method.invoke(Method.java:372)

W/System.err( 8134): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)

W/System.err( 8134): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)

F/chromium( 8134): [FATAL:jni_android.cc(306)] Please include Java exception stack in crash report
```
(I searched "crash" in the file and found those)

**Comment by csagan5** [comment]
@ygz213 you submitted half of it, the part above this is necessary:
```
W/System.err( 8134): 	at hh.b(chromium-ChromePublic.apk-stable-1622851880:10)
W/System.err( 8134): 	at ch.b(chromium-ChromePublic.apk-stable-1622851880:3)
W/System.err( 8134): 	at go1.a(chromium-ChromePublic.apk-stable-1622851880:1)
W/System.err( 8134): 	at dh.c(chromium-ChromePublic.apk-stable-1622851880:8)
W/System.err( 8134): 	at org.chromium.chrome.browser.download.service.DownloadTaskScheduler.scheduleTask(chromium-ChromePublic.apk-stable-1622851880:14)
W/System.err( 8134): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 8134): 	at android.os.MessageQueue.next(MessageQueue.java:148)
W/System.err( 8134): 	at android.os.Looper.loop(Looper.java:151)
W/System.err( 8134): 	at android.app.ActivityThread.main(ActivityThread.java:5576)
W/System.err( 8134): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 8134): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 8134): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
W/System.err( 8134): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
F/chromium( 8134): [FATAL:jni_android.cc(306)] Please include Java exception stack in crash report
D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0
D/hwcomposer(  141): [HWC] prepare_primary==
E/chromium( 8806): [0607/114558.541847:ERROR:elf_dynamic_array_reader.h(61)] tag not found
I/SurfaceFlinger(  141): [Built-in Screen (type:0)] fps:41.732475,dur:1054.33,max:199.97,min:16.44
D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0
D/hwcomposer(  141): [HWC] prepare_primary==
E/chromium( 8806): [0607/114558.671786:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: Permission denied (13)
E/chromium( 8806): [0607/114558.676586:ERROR:system_snapshot_linux.cc(126)] Couldn't read property ro.product.board
F/libc    ( 8134): Fatal signal 5 (SIGTRAP), code -6 in tid 8134 (bromite.bromite)
I/libc    ( 8134): Suppressing debuggerd output because prctl(PR_GET_DUMPABLE)==0
```

**Comment by radorn** [comment]
I also have this problem. Android 5.0.2.
Not only does Bromite crash on downloading files; but it also crashes if a site fails to load due to lack of network acess (wifi/cellular), be it because it's disabled or due to signal loss.
version 91.0.4472.97

**Comment by radorn** [comment]
I just found out that if the downloaded file is small enough, it gets downloaded correctly, but the app still crashes. Large files still crash. I don't know the actual threshold, but , I could DL ~150kb files, while multi-mega files fail.

**Comment by ygz213** [comment]
```
W/cr_DownloadFg( 8134): Checking if delayed stopAndUnbindService needs to be resolved.

W/cr_DownloadFg( 8134): Done checking if delayed stopAndUnbindService needs to be resolved.

I/BufferQueueProducer(  141): [StatusBar](this:0xb6333800,id:8,api:1,p:865,c:141) queueBuffer: fps=1.00 dur=2005.07 max=1908.47 min=96.60

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

I/ANRManager(  548): CPU update time < 2.5sec

I/ANRManager(  548): CPU update time < 2.5sec

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

D/SocketClient(  149): SocketClient sendData done: 601 limit alert globalAlert wlan0

D/NetworkManagementService(  548): onEvent:601 limit alert globalAlert wlan0:5

V/SettingsInterface(  548):  from settings cache , name = netstats_time_cache_max_age , value = null

D/PowerManagerService(  548): acquireWakeLockInternal: lock=774907371, flags=0x1, tag="NetworkStats", ws=null, uid=1000, pid=548

D/PowerManagerService(  548): updateWakeLockSummaryLocked: mWakefulness=Awake, mWakeLockSummary=0x1

D/PowerManagerService(  548): updateUserActivitySummaryLocked: mWakefulness=Awake, mUserActivitySummary=0x1, nextTimeout=45367870 (in 52059 ms)

D/PowerManagerService(  548): mDisplayPowerRequest.policy = 3

D/WifiDisplayAdapter(  548): getWifiDisplayStatusLocked: result=WifiDisplayStatus{featureState=2, scanState=0, activeDisplayState=0, activeDisplay=null, displays=[], sessionInfo=WifiDisplaySessionInfo: C/O:Client,GId:,Pp:,SId:0,IP:}

D/PowerManagerService(  548): isWfdEnabled() mWfdStatus=WifiDisplayStatus{featureState=2, scanState=0, activeDisplayState=0, activeDisplay=null, displays=[], sessionInfo=WifiDisplaySessionInfo: C/O:Client,GId:,Pp:,SId:0,IP:}, return false

D/DisplayPowerController(  548): requestPowerState: policy=BRIGHT, useProximitySensor=false, screenBrightness=56, screenAutoBrightnessAdjustment=0.0, useAutoBrightness=false, blockScreenOn=false, lowPowerMode=false, dozeScreenBrightness=-1, dozeScreenState=UNKNOWN, waitForNegativeProximity=false

I/PowerManagerService(  548): setBrightness mButtonLight 0.

D/PowerManagerService(  548): updateScreenStateLocked: mDisplayReady=true, policy=3, mWakefulness=1, mWakeLockSummary=0x1, mUserActivitySummary=0x1, mBootCompleted=true

D/PowerManagerService(  548): Acquiring suspend blocker "PowerManagerService.WakeLocks".

D/PowerManagerNotifier(  548): onWakeLockAcquired: flags=1, tag="NetworkStats", packageName=android, ownerUid=1000, ownerPid=548, workSource=null

V/NetworkStats(  548): performPollLocked(flags=0x1)

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

D/NetdConnector(  548): SND -> {297 bandwidth gettetherstats}

D/FrameworkListener(  149): dispatchCommand data = (297 bandwidth gettetherstats)

D/SocketClient(  149): SocketClient sendData done: 200 297 Tethering stats list completed

D/NetdConnector(  548): RMV <- {200 297 Tethering stats list completed}

W/NetworkStatsRecorder(  548): unknown interfaces [tun0, lo, p2p0], ignoring those stats

W/NetworkStatsRecorder(  548): unknown interfaces [tun0, lo, p2p0], ignoring those stats

W/NetworkStatsRecorder(  548): unknown interfaces [tun0, lo, p2p0], ignoring those stats

W/NetworkStatsRecorder(  548): unknown interfaces [tun0, lo, p2p0], ignoring those stats

D/NetworkStatsRecorder(  548): forcePersistLocked() writing for dev

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

D/NetworkStatsRecorder(  548): forcePersistLocked() writing for xt

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/ANRManager(  548): CPU update time < 2.5sec

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

V/NetworkStats(  548): performPollLocked() took 79ms

V/SettingsInterface(  548):  from settings cache , name = netstats_sample_enabled , value = null

V/ActivityManager(  548): Broadcast: Intent { act=com.android.server.action.NETWORK_STATS_UPDATED flg=0x40000010 } ordered=false userid=-1 callerApp=ProcessRecord{24be305c 548:system/1000}

D/PowerManagerService(  548): releaseWakeLockInternal: lock=774907371 [NetworkStats], flags=0x0, total_time=84ms

D/PowerManagerNotifier(  548): onWakeLockReleased: flags=1, tag="NetworkStats", packageName=android, ownerUid=1000, ownerPid=548, workSource=null

D/PowerManagerService(  548): updateWakeLockSummaryLocked: mWakefulness=Awake, mWakeLockSummary=0x0

D/PowerManagerService(  548): updateUserActivitySummaryLocked: mWakefulness=Awake, mUserActivitySummary=0x1, nextTimeout=45367870 (in 51975 ms)

D/PowerManagerService(  548): mDisplayPowerRequest.policy = 3

D/WifiDisplayAdapter(  548): getWifiDisplayStatusLocked: result=WifiDisplayStatus{featureState=2, scanState=0, activeDisplayState=0, activeDisplay=null, displays=[], sessionInfo=WifiDisplaySessionInfo: C/O:Client,GId:,Pp:,SId:0,IP:}

D/PowerManagerService(  548): isWfdEnabled() mWfdStatus=WifiDisplayStatus{featureState=2, scanState=0, activeDisplayState=0, activeDisplay=null, displays=[], sessionInfo=WifiDisplaySessionInfo: C/O:Client,GId:,Pp:,SId:0,IP:}, return false

D/DisplayPowerController(  548): requestPowerState: policy=BRIGHT, useProximitySensor=false, screenBrightness=56, screenAutoBrightnessAdjustment=0.0, useAutoBrightness=false, blockScreenOn=false, lowPowerMode=false, dozeScreenBrightness=-1, dozeScreenState=UNKNOWN, waitForNegativeProximity=false

I/PowerManagerService(  548): setBrightness mButtonLight 0.

D/PowerManagerService(  548): updateScreenStateLocked: mDisplayReady=true, policy=3, mWakefulness=1, mWakeLockSummary=0x0, mUserActivitySummary=0x1, mBootCompleted=true

D/PowerManagerService(  548): Releasing suspend blocker "PowerManagerService.WakeLocks".

D/NetdConnector(  548): SND -> {298 bandwidth setglobalalert 2097152}

D/FrameworkListener(  149): dispatchCommand data = (298 bandwidth setglobalalert 2097152)

D/SocketClient(  149): SocketClient sendData done: 200 298 Bandwidth command succeeeded

D/NetdConnector(  548): RMV <- {200 298 Bandwidth command succeeeded}

V/NetworkPolicy(  548): updateNetworkEnabledLocked()

V/SettingsInterface( 1106):  from settings cache , name = multi_sim_data_call , value = null

V/NetworkPolicy(  548): updateNotificationsLocked()

V/SettingsInterface( 1106):  from settings cache , name = multi_sim_data_call , value = null

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/BufferQueueProducer(  141): [org.bromite.bromite/com.google.android.apps.chrome.Main](this:0xb1c75400,id:575,api:1,p:8134,c:141) queueBuffer: fps=35.30 dur=1019.70 max=349.67 min=6.48

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/SurfaceView( 8134): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{db333e8 V.E..... ........ 0,0-1280,703}

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

D/ConnectivityService(  548): getActiveNetworkInfo:[type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: "FiberHGW_ZT5F53_2.4GHz", roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false]/10087

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

D/ConnectivityService(  548): getActiveNetworkInfo:[type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: "FiberHGW_ZT5F53_2.4GHz", roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false]/10087

E/cr_BTSPrefs( 8134): No data found for task id: 57

E/cr_BkgrdTaskScheduler( 8134): Task cannot be canceled because no data was found instorage or data was invalid

W/System.err( 8134): java.lang.IllegalAccessError: Method 'void android.os.BaseBundle.putBoolean(java.lang.String, boolean)' is inaccessible to class 'hh' (declaration of 'hh' appears in /data/app/org.bromite.bromite-1/base.apk)

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

I/ANRManager(  548): CPU update time < 2.5sec

W/System.err( 8134): 	at hh.b(chromium-ChromePublic.apk-stable-1622851880:10)

W/System.err( 8134): 	at ch.b(chromium-ChromePublic.apk-stable-1622851880:3)

W/System.err( 8134): 	at go1.a(chromium-ChromePublic.apk-stable-1622851880:1)

W/System.err( 8134): 	at dh.c(chromium-ChromePublic.apk-stable-1622851880:8)

W/System.err( 8134): 	at org.chromium.chrome.browser.download.service.DownloadTaskScheduler.scheduleTask(chromium-ChromePublic.apk-stable-1622851880:14)

W/System.err( 8134): 	at android.os.MessageQueue.nativePollOnce(Native Method)

W/System.err( 8134): 	at android.os.MessageQueue.next(MessageQueue.java:148)

W/System.err( 8134): 	at android.os.Looper.loop(Looper.java:151)

W/System.err( 8134): 	at android.app.ActivityThread.main(ActivityThread.java:5576)

W/System.err( 8134): 	at java.lang.reflect.Method.invoke(Native Method)

W/System.err( 8134): 	at java.lang.reflect.Method.invoke(Method.java:372)

W/System.err( 8134): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)

W/System.err( 8134): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)

F/chromium( 8134): [FATAL:jni_android.cc(306)] Please include Java exception stack in crash report

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

E/chromium( 8806): [0607/114558.541847:ERROR:elf_dynamic_array_reader.h(61)] tag not found

I/SurfaceFlinger(  141): [Built-in Screen (type:0)] fps:41.732475,dur:1054.33,max:199.97,min:16.44

D/hwcomposer(  141): [HWC] hdmi connect=0, isDecoupleOvl=0

D/hwcomposer(  141): [HWC] prepare_primary==

E/chromium( 8806): [0607/114558.671786:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: Permission denied (13)

E/chromium( 8806): [0607/114558.676586:ERROR:system_snapshot_linux.cc(126)] Couldn't read property ro.product.board

F/libc    ( 8134): Fatal signal 5 (SIGTRAP), code -6 in tid 8134 (bromite.bromite)

I/libc    ( 8134): Suppressing debuggerd output because prctl(PR_GET_DUMPABLE)==0
```

**Comment by uazo** [comment]
with `../chromium/src/build/android/stacktrace/java_deobfuscate.py ChromePublic.apk.mapping <trace`

```
W/System.err( 8134): java.lang.IllegalAccessError: Method 'void android.os.BaseBundle.putBoolean(java.lang.String, boolean)' is inaccessible to class 'hh' (declaration of 'hh' appears in /data/app/org.bromite.bromite-1/base.apk)
W/System.err( 8134):    at org.chromium.components.background_task_scheduler.internal.BundleToPersistableBundleConverter.convert(BundleToPersistabeBundleConverter.java:88)
W/System.err( 8134):    at org.chromium.components.background_task_scheduler.internal.BackgroundTaskSchedulerJobService.getTaskExtrasAsPersistableBundle(BackgroundTaskSchedulerJobService.java:207)
W/System.err( 8134):    at org.chromium.components.background_task_scheduler.internal.BackgroundTaskSchedulerJobService.createJobInfoFromTaskInfo(BackgroundTaskSchedulerJobService.java:119)
W/System.err( 8134):    at org.chromium.components.background_task_scheduler.internal.BackgroundTaskSchedulerJobService.schedule(BackgroundTaskSchedulerJobService.java:220)
W/System.err( 8134):    at org.chromium.components.background_task_scheduler.internal.BackgroundTaskSchedulerImpl$SchedulingVisitor.visit(BackgroundTaskSchedulerImpl.java:88)
W/System.err( 8134):    at org.chromium.chrome.modules.test_dummy.TestDummyModule.a(TestDummyModule.java:1)
W/System.err( 8134):    at org.chromium.components.background_task_scheduler.internal.BackgroundTaskSchedulerImpl.schedule(BackgroundTaskSchedulerImpl.java:55)
W/System.err( 8134):    at org.chromium.chrome.browser.download.service.DownloadTaskScheduler.scheduleTask(DownloadTaskScheduler.java:53)
W/System.err( 8134):    at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
W/System.err( 8134):    at android.os.MessageQueue.next(MessageQueue.java:148)
W/System.err( 8134):    at android.os.Looper.loop(Looper.java:151)
W/System.err( 8134):    at android.app.ActivityThread.main(ActivityThread.java:5576)
W/System.err( 8134):    at java.lang.reflect.Method.invoke(Method.java)
W/System.err( 8134):    at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 8134):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
W/System.err( 8134):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
```

in my opinion it is an upstream bug.
sure that in chromium it works?

**Comment by radorn** [comment]
@uazo @csagan5 I'm not the OP but, as I said before, I have the same problem. 
I just used yet another browser to DL the chromium apk you have in the other repo and DLs work fine from it too, so it seems to me the that it is bromite after all.

**Comment by ygz213** [comment]
> in my opinion it is an upstream bug.
sure that in chromium it works?

I tried a download on <https://www.bromite.org/chromium>'s Chromium and finished successfully.

**Comment by csagan5** [comment]
> I also have this problem. Android 5.0.2.
> Not only does Bromite crash on downloading files; but it also crashes if a site fails to load due to lack of network access (wifi/cellular), be it because it's disabled or due to signal loss.
> version 91.0.4472.97

You have to submit a separate issue if it fails when there is no network.

> in my opinion it is an upstream bug.

https://developer.android.com/reference/android/os/BaseBundle#putBoolean(java.lang.String,%20boolean) says it was added in API level 22, how did it end up being called on 5.0 (level 21)? it looks like it's there since 2017; this is puzzling.

**Comment by uazo** [comment]
> says it was added in API level 22, how did it end up being called on 5.0 (level 21)? it looks like it's there since 2017; this is puzzling.

maybe the problem is here

`
W/System.err( 8134):    at org.chromium.chrome.modules.test_dummy.TestDummyModule.a(TestDummyModule.java:1)
`

I imagine it is the patch that disables google stuffs, because I had seen that some api were emulated by google in old devices.
I try to check.

**Comment by csagan5** [comment]
> maybe the problem is here
> 
> `W/System.err( 8134): at org.chromium.chrome.modules.test_dummy.TestDummyModule.a(TestDummyModule.java:1)`
> 
> I imagine it is the patch that disables google stuffs, because I had seen that some api were emulated by google in old devices.
> I try to check.

I noticed that `TestDummyModule`, but I do not understand how it is being invoked. It is not explicitly done by Bromite patches.

**Comment by ygz213** [comment]
This must reopen.

**Comment by ygz213** [comment]
Why is you don't reopen this issue?
I think this is a important problem. Now I must delete :\

**Comment by uazo** [comment]
@ygz213 the fact that it is still closed does not mean that it will not be taken into consideration, please have the patience and respect for those who as a volunteer may not have time available.
furthermore, this bug is complex and resolution is never guaranteed

**Comment by csagan5** [comment]
The bug will be re-opened when it is confirmed/reproducible.

**Comment by ygz213** [comment]
Isn't the crash already too reproducible? (on each download) @csagan5

**Comment by uazo** [comment]
> The bug will be re-opened when it is confirmed/reproducible.

tried with x86_64 android 5.1 emulator, it works correctly without any crash
I need some more info to reproduce the error

**Comment by ygz213** [comment]
Like what?

**Comment by csagan5** [comment]
@ygz213 if I were to buy a TCL-8079, how would I get a device same as yours? Which ROM does it come with?

**Comment by ygz213** [comment]
ROM is <https://www.alcatelmobile.com/support/software-drivers/> (PIXI3-10) or <https://alcatelfirmware.com/alcatel-onetouch-pixi-3-8079/>

Unfortunately, I can't try because I don't know how to install ROMs.

**Comment by uazo** [comment]
> https://alcatelfirmware.com/alcatel-onetouch-pixi-3-8079/

sorry for my ignorance on the subject, 5.0.1 is not 5.1!
just tried it actually crashes with that error, while chromium doesn't

**Comment by uazo** [comment]
@csagan5  here the real stack trace:
```
W/System.err( 3562): java.lang.IllegalAccessError: Method 'void android.os.BaseBundle.putBoolean(java.lang.String, boolean)' is inaccessible to class 'org.chromium.components.background_task_scheduler.internal.BundleToPersistableBundleConverter' (declaration of 'org.chromium.components.background_task_scheduler.internal.BundleToPersistableBundleConverter' appears in /data/app/org.chromium.chrome.stable-1/base.apk:classes3.dex)
W/System.err( 3562):    at org.chromium.components.background_task_scheduler.internal.BundleToPersistableBundleConverter.convert(BundleToPersistableBundleConverter.java:88)
W/System.err( 3562):    at org.chromium.components.background_task_scheduler.internal.BackgroundTaskSchedulerJobService.getTaskExtrasAsPersistableBundle(BackgroundTaskSchedulerJobService.java:207)
W/System.err( 3562):    at org.chromium.components.background_task_scheduler.internal.BackgroundTaskSchedulerJobService.createJobInfoFromTaskInfo(BackgroundTaskSchedulerJobService.java:119)
W/System.err( 3562):    at org.chromium.components.background_task_scheduler.internal.BackgroundTaskSchedulerJobService.schedule(BackgroundTaskSchedulerJobService.java:220)
W/System.err( 3562):    at org.chromium.components.background_task_scheduler.internal.BackgroundTaskSchedulerImpl$SchedulingVisitor.visit(BackgroundTaskSchedulerImpl.java:88)
W/System.err( 3562):    at org.chromium.components.background_task_scheduler.TaskInfo$OneOffInfo.accept(TaskInfo.java:124)
W/System.err( 3562):    at org.chromium.components.background_task_scheduler.internal.BackgroundTaskSchedulerImpl.schedule(BackgroundTaskSchedulerImpl.java:55)
W/System.err( 3562):    at org.chromium.chrome.browser.download.service.DownloadTaskScheduler.scheduleTask(DownloadTaskScheduler.java:53)
W/System.err( 3562):    at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 3562):    at android.os.MessageQueue.next(MessageQueue.java:143)
W/System.err( 3562):    at android.os.Looper.loop(Looper.java:122)
W/System.err( 3562):    at android.app.ActivityThread.main(ActivityThread.java:5221)
W/System.err( 3562):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 3562):    at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 3562):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
W/System.err( 3562):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

there is none `TestDummyModule`, maybe `java_deobfuscate.py` it's not very reliable

**Comment by uazo** [comment]
it is as I told you, the disabling of gcm has to do with it:

![image](https://user-images.githubusercontent.com/29201891/123424803-9f1fd500-d5c1-11eb-9c6c-26aa6e44efcd.png)

chromium on the left, bromite on the right
then chromium goes into closed source:

![image](https://user-images.githubusercontent.com/29201891/123424991-d55d5480-d5c1-11eb-90f1-d1b22b893048.png)

tips?

**Comment by uazo** [comment]
> says it was added in API level 22, how did it end up being called on 5.0 (level 21)? it looks like it's there since 2017; this is puzzling.

@csagan5 i tried bromite v78, same crash there too
if no one has any ideas i guess it will be a wont-fix

**Comment by csagan5** [comment]
> here the real stack trace:

@uazo how did you produce this new one?

> it is as I told you, the disabling of gcm has to do with it:

You also provided the stacktrace which was not correct, that is why we need to work with reproducible results; my bad for not reproducing that stacktrace.

This is when the scheduler was introduced: https://github.com/chromium/chromium/commit/8a9fdb7818cf338102a0c1c889d19da5f704399a

Note in the comments:
> We prefer system APIs, since they do not require including
external libraries which bloats the APK size of Chrome and adds unnecessary
complexity. The GcmNetworkManager is only used when the system API is not
available.

The limitation is also explained there:
> The {@link android.app.job.JobScheduler} API requires the use of {@link PersistableBundle} in
> the {@link android.app.job.JobInfo}, but that was added in API 21 (Lollipop). A later change
> related to booleans means that this class required API 22 (Lollipop MR1).
> the API of the {@link BackgroundTaskScheduler} needs to take a {@link Bundle}, but convert it to
> a {@link PersistableBundle} in the case of using {@link android.app.job.JobScheduler} as the
> backend for scheduling.

So it looks like Chromium has always used GcmNetworkManager on API 21?

**Comment by uazo** [comment]
> @uazo how did you produce this new one?

with android emulator and A5.0 x86 image

> You also provided the stacktrace which was not correct, 

intrigued, I went to check that led me to this:
https://source.chromium.org/chromium/chromium/src/+/main:chrome/android/java/AndroidManifest.xml;l=1170

but the current (bromite) version also has `if`
```
        {% if min_sdk_version|int >= 21 %}
        <activity
            android:name="org.chromium.chrome.browser.test_dummy.TestDummyActivity"
            android:excludeFromRecents="true"
            android:exported="true"
            android:noHistory="true"
            android:theme="@style/Theme.AppCompat"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|mcc|mnc|screenLayout|smallestScreenSize" >
        </activity>
        {% endif %}
```
I think it is simply due to the fact that I do not impose anything in the GN in my debug version, maybe you do, so `java_deobfuscate.py` seems to work

> The limitation is also explained there:

yes i also tried some workaround found in internet, but nothing works.

> So it looks like Chromium has always used GcmNetworkManager on API 21?

yes, it seems so.

**Comment by csagan5** [comment]
> > The limitation is also explained there:
> 
> yes i also tried some workaround found in internet, but nothing works.

Have you checked what are the boolean properties (or boolean array properties) that it is trying to set?

I am going to do some tests.

**Comment by uazo** [comment]
are you going to check how necessary that code is? perfect, the idea I was missing,
no, I haven't tried, but it's an interesting approach.

**Comment by csagan5** [comment]
> are you going to check how necessary that code is? perfect, the idea I was missing,
> no, I haven't tried, but it's an interesting approach.

It looks like I cannot: Android Studio has only v5.0.2 and I cannot reproduce the crash with that one.

We could either remove the boolean properties or put them as `Long`, since the conversion should work when they are read back.

**Comment by uazo** [comment]
i'm trying with a `try-catch`, we see that `key` would be missing

> We could either remove the boolean properties or put them as Long, since the conversion should work when they are read back.

next step.

**Comment by uazo** [comment]
you may not believe it, but you were right, with:

```
diff --git a/components/background_task_scheduler/internal/android/java/src/org/chromium/components/background_task_scheduler/internal/BundleToPersistableBundleConverter.java b/components/background_task_scheduler/internal/android/java/src/org/chromium/components/background_task_scheduler/internal/BundleToPersistableBundleConverter.java
index 0e16236e37..71bf9ee617 100644
--- a/components/background_task_scheduler/internal/android/java/src/org/chromium/components/background_task_scheduler/internal/BundleToPersistableBundleConverter.java
+++ b/components/background_task_scheduler/internal/android/java/src/org/chromium/components/background_task_scheduler/internal/BundleToPersistableBundleConverter.java
@@ -14,6 +14,8 @@ import androidx.annotation.NonNull;
 import java.util.HashSet;
 import java.util.Set;

+import org.chromium.base.Log;
+
 /**
  * Converts from {@link Bundle} to {@link PersistableBundle}.
  *
@@ -82,6 +84,7 @@ class BundleToPersistableBundleConverter {
         Set<String> failedKeys = new HashSet<>();
         for (String key : bundle.keySet()) {
             Object obj = bundle.get(key);
+            try {
             if (obj == null) {
                 persistableBundle.putString(key, null);
             } else if (obj instanceof Boolean) {
@@ -107,6 +110,10 @@ class BundleToPersistableBundleConverter {
             } else {
                 failedKeys.add(key);
             }
+            } catch(IllegalAccessError e) {
+                Log.i("BundleToPersistableBundleConverter",
+                    "failed to apply " + key);
+            }
         }
         return new Result(persistableBundle, failedKeys);
     }

```
and this log
```
I/cr_BundleToPersistableBundleConverter( 4319): failed to apply UnmeteredNetwork
I/cr_BundleToPersistableBundleConverter( 4319): failed to apply PowerConnected
```
everything works perfectly!

**Comment by csagan5** [comment]
@uazo thanks for testing this; how did you download a `5.0.1` ROM? I cannot reproduce this bug with `5.0.2`.

I will release a similar patch on next version, so that API level 21 is still supported.

**Comment by uazo** [comment]
> thanks for testing this

I don't have to apologize, you don't need to thank!

>  how did you download a 5.0.1 ROM? 

ah, yes, I forgot.. I have not encountered any problems, just a click away ..
![image](https://user-images.githubusercontent.com/29201891/123552305-d800ab00-d775-11eb-94d4-1b515817f4e3.png)

**Comment by csagan5** [comment]
> ah, yes, I forgot.. I have not encountered any problems, just a click away ..

Is that one 5.0.2 or 5.0.1? I got 5.0.2 here.

**Comment by csagan5** [comment]
@uazo please let me know about the above ^

**Comment by csagan5** [comment]
Fixed in `91.0.4472.146`.

**Comment by uazo** [comment]
> Is that one 5.0.2 or 5.0.1? I got 5.0.2 here.

yes, you're right, but it was crashing anyway, weird.

![image](https://user-images.githubusercontent.com/29201891/123749707-02f21880-d8b6-11eb-9f1d-4c20c71b170b.png)

**Comment by radorn** [comment]
Worked for me too, and also fixed the other problem I mentioned about crashing when offline.
Thank you so much.

**Comment by ygz213** [comment]
Thanks a lot for fix.
