### ISSUE TITLE
Application doesn't close on closing the incognito tab. Instead opens the normal tab.

### ISSUE THREAD

**Issue by pixincreate** [bromite/bromite#1503]
### Bromite version

Version: `94.0.4606.102`
Arch: `arm64`
Android version:  based on Lineage OS
Device model: Nokia 6. Plus

### Flags

These are the flags changed under `chrome://flags`:
None

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is this bug happening in an incognito tab?
Yes

### Allow ads for the site; is the bug caused by the adblocker?
No

### Is the bug a crash?

No

### Describe the bug

@csagan5, @uazo. It is nice to the features implemented and got the bugs fixed. Special thanks for that.  Can you make the application (intent?) close once you hit back button?    
Lemme explain:   
- I open a external link
- It opens in Incognito Mode (1st search)
- I search something other from the same tab (2nd search)
- I'm done doing my stuffs, now, I hit back, it should go to 1st search, again hitting back button should close the app altogether instead of opening the Normal Tabs and forcing me to close the app manually.
 ____
And another thing that I noticed is, sometimes, closing app by clearing RAM closes the incognito tab which does the job pretty well. How ever, it doesn't remove "close incognito tab" notification.   
____
I feel like this is a bug.
  
### Steps to reproduce the bug

Steps to reproduce the bug:
1.  I open a external link
2. It opens in Incognito Mode (1st search)
3.  I search something other from the same tab (2nd search)
4.  I'm done doing my stuffs, now, I hit back, it should go to 1st search, again hitting back button should close the app altogether instead of opening the Normal Tabs and forcing me to close the app manually.

Do not write "any website", specify which URLs can be used to reproduce the issue.

### Expected behavior

  
After I'm done browsing in the incognito mode that was opened from an external limk, Hitting back, should close the app instead of opening the normal tab' home page.   
And closing app from Recent menu, do close the tabs butnot the incognito notification in the status bar.

**Comment by csagan5** [comment]
Fixed in `95.0.4638.78`.

**Comment by uazo** [comment]
@pixincreate can you try if it is actually solved?

**Comment by pixincreate** [comment]
Yes. It resolved the issue but the incognito notification still exist

**Comment by uazo** [comment]
> Yes. It resolved the issue but the incognito notification still exist

but that is an upstream bug, if they don't fix it in the next versions we'll think about it.

**Comment by uazo** [comment]
> if they don't fix it in the next versions we'll think about it.

it seems to me that in v96 it is fixed.

**Comment by pixincreate** [comment]
I just checked it again, unfortunately, that notification still exist for me, and I'm on the latest version. I can share the screenshot with you if you've doubt regarding that (whether it's device specific or not, IMO, it isn't)

**Comment by csagan5** [comment]
@uazo is it reproducible for you?

**Comment by pixincreate** [comment]
> I just checked it again, unfortunately, that notification still exist for me, and I'm on the latest version. I can share the screenshot with you if you've doubt regarding that (whether it's device specific or not, IMO, it isn't)

This is still reproducible

**Comment by uazo** [comment]
> is it reproducible for you?

yes, the user is right. the way we close the application is probably wrong.

**Comment by csagan5** [comment]
Ok; can you tell in which patch the bug is and which files could be involved? So that someone can work on a fix.

**Comment by uazo** [comment]
> can you tell in which patch the bug 

no bugs in any patch

>  So that someone can work on a fix.

basically to fix it permanently you should create a new service in the foreground and `onTaskRemoved` remove the notification

**Comment by csagan5** [comment]
> > can you tell in which patch the bug
> 
> no bugs in any patch
> 
> > So that someone can work on a fix.
> 
> basically to fix it permanently you should create a new service in the foreground and `onTaskRemoved` remove the notification

And this would fix also the upstream bug with the notification?

**Comment by uazo** [comment]
> And this would fix also the upstream bug with the notification?

Yes sure

**Comment by uazo** [comment]
> And this would fix also the upstream bug with the notification?

see https://bugs.chromium.org/p/chromium/issues/detail?id=753920

**Comment by csagan5** [comment]
> > And this would fix also the upstream bug with the notification?
> 
> see https://bugs.chromium.org/p/chromium/issues/detail?id=753920

Ok, this would be the upstream proper fix; since in v98 we have your patch now I will close this issue as there is nothing else we can fix in Bromite.

Fixed in `98.0.4758.108`.
