### ISSUE TITLE
Malfunctioning sticky desktop mode

### ISSUE THREAD

**Issue by rdj0im** [bromite/bromite#2179]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

102.0.5005.96

### Device architecture

arm64-v8a

### Android version

11

### Device model

Redmi 9 M2006C3MII

### Changed flags

enable-tab-groups

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

Desktop mode doesn't stick and is disabled with opening of each new tab. When "Current behaviour for desktop mode toggle in hamburger menu" is set to "Applies to all tabs" (sticky mode) and desktop mode is enabled, opening a new tab causes all tabs (including current tab) to be switched back to normal mode, instead of the new tabs being opened in desktop mode. Also Desktop mode doesn't persist between sessions like it used to.

### Steps to reproduce the bug

1. Set "Current behaviour for desktop mode toggle in hamburger menu" in "Customize User Agent" setting to Applies to all tabs" (sticky mode).
2. Open a tab.
3. Enable Desktop mode in hamburger menu.
4. Open any site in another tab.

### Expected behavior

New tabs would be opened in Desktop mode and ones already in Desktop mode would remain so until I explicitly turn off desktop mode in the hamburger menu.

**Comment by uazo** [comment]
thanks, I confirm the bug. I will check

**Comment by csagan5** [comment]
Fixed in `103.0.5060.126`.

**Comment by rdj0im** [comment]
It still isn't functioning exactly as it used to, i think. On opening new tabs with sticky mode and the desktop mode checkbox already checked,the desktop mode checkbox is checked and I get the desktop mode resolution but sites still serve me the mobile version of their site (for example reddit). But for tabs which I switch from mobile to desktop mode manually and I make the switch after the tabs are already open, this works properly and i get the desktop version of the site. Maybe the correct user agent string is not being sent in the former case or something? Could you please look into it or need I open a new issue?

**Comment by uazo** [comment]
> Maybe the correct user agent string is not being sent in the former case or something? 

@rdj0im Yes you are right. I focused on the viewport and not the network layer, I'll check.

**Comment by csagan5** [comment]
@uazo please re-open if bug is not yet fixed (or we need a new issue).

**Comment by uazo** [comment]
> please re-open if bug is not yet fixed

same for @rdj0im
