### ISSUE TITLE
Bromite Web View Crash on 71.0.3578.120

### ISSUE THREAD

**Issue by Nickdv9** [bromite/bromite#219]
**Bromite webview version**

Version: `71.0.3578.120`
Arch: `arm64`
Android version: `9.0`

**Is the bug reproducible with latest version?**
`Yes`

**Is the bug a crash?**
`Yes, log is attached below`
[bromitewebview.txt](https://github.com/bromite/bromite/files/2733756/bromitewebview.txt)

**Describe the bug**
Apps that use webview start crashing on this version

**Steps to reproduce the behavior:**
Open any app that uses webview

**Expected behavior**
All apps that use webview must open normally without any crash

**Comment by guest4711** [comment]
Same for me on arm (32 Bit).

**Comment by csagan5** [comment]
@Nickdv9 @guest4711 can you test with this pre-release version? https://github.com/bromite/bromite/releases/tag/71.0.3578.123

If it still crashes I would need the logcat logs as well.

**Comment by guest4711** [comment]
Just downloading, thanks. Will check soon.

**Comment by guest4711** [comment]
K9-Mail chrashed again with current webview. Matlog attached.

**Comment by guest4711** [comment]
[2019-01-08-00-11-25.txt](https://github.com/bromite/bromite/files/2734666/2019-01-08-00-11-25.txt)
[2019-01-08-00-24-44.txt](https://github.com/bromite/bromite/files/2734670/2019-01-08-00-24-44.txt)

**Comment by csagan5** [comment]
@guest4711 seems like your logs do not contain the crash logs, they are disabled. Also you should not post your full logcats like that on the internet, it is not privacy-safe; I suggest removing them.

It is sufficient to post only the crash of Bromite, like here: https://github.com/bromite/bromite/files/2734414/adb-logcat-2.txt

There should be a new .123 build appearing soon here: https://github.com/bromite/bromite/releases/tag/71.0.3578.123
Hopefully that one will have the crash issue fixed.

**Comment by Nickdv9** [comment]
@csagan5 current build here https://github.com/bromite/bromite/releases/tag/71.0.3578.123 is the latest pre-release or old one?

**Comment by lowtrucks** [comment]
@Nickdv9, it's not compiled yet.

**Comment by Nickdv9** [comment]
@csagan5 Tried the latest `arm64_SystemWebView.apk` and seems like crash isn't fixed yet. Error looks the same. Attaching log below.
[bromitewebview.txt](https://github.com/bromite/bromite/files/2736373/bromitewebview.txt)

**Comment by csagan5** [comment]
@Nickdv9 the issue should be solved with latest .123 build, can you confirm/deny?

**Comment by Nickdv9** [comment]
@csagan5 I'll surely test as soon as its compiled. I don't see a webview as of now

**Comment by DragoCubed** [comment]
I'm glad I came here right after I saw it crashing incessantly. I hope the new version gets uploaded to the F-droid repo.

**Comment by csagan5** [comment]
Fixed in `71.0.3578.123`

**Comment by guest4711** [comment]
Confirmed working on arm.

**Comment by pwn0r** [comment]
just in case -- this issue (or very similar, the end result is same -- webview crashed on any page) is not solved in .123. LOS15.1 arm64 here. 

Just for testing purposes -- I had to completely remove the bromite webview, because for whatever reason I was unable to downgrade. So removing all webview, then installing .110 -- all works. Both wikipedia app and webview test work. Then upgrade to .123, reboot, and webview crashes all the time.

**Comment by csagan5** [comment]
@pwn0r can you verify the version of the SystemWebView installed? you might want to open a new issue about this and attach the crash logs otherwise nothing can be done for troubleshooting it
