### ISSUE TITLE
F-droid repository not working anymore

### ISSUE THREAD

**Issue by marcoismobile** [bromite/bromite#378]
I don't know how to contact otherwise, so I will do it through a github issue.

The F-Droid bromite repository isn't working anymore (hangs on contacting). After some troubleshooting I got the following error when doing a curl to the repo URL:

```
~ » curl -vL https://fdroid.bromite.org/fdroid/repo
*   Trying 185.199.110.153:443...
* TCP_NODELAY set
* Connected to fdroid.bromite.org (185.199.110.153) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=www.github.com
*  start date: Jun 27 00:00:00 2018 GMT
*  expire date: Jun 20 12:00:00 2020 GMT
*  subjectAltName does not match fdroid.bromite.org
* SSL: no alternative certificate subject name matches target host name 'fdroid.bromite.org'
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, close notify (256):
curl: (60) SSL: no alternative certificate subject name matches target host name 'fdroid.bromite.org'
More details here: https://curl.haxx.se/docs/sslcerts.html
```

So it seems the SSL certificate isn't valid for the **fdroid.bromite.org** domain.

Is this a known issue? It's not working for at least 2 days as far as I can tell.

Hope I can install the amazing Bromite on my new android phone from f-droid soon again ;)

Thanks in advance!

**Comment by casoncobi** [comment]
@csagan5 After you've updated CNAME (LGTM), you need to

1. remove your custom domain and then 
2. re-add your custom domain

to trigger the process of enabling HTTPS for custom domain, as per those instructions (at the bottom, section 4):
https://help.github.com/en/articles/setting-up-an-apex-domain

**Comment by SimonBrazell** [comment]
Workaround - use HTTP instead of HTTPS for repo URL.

**Comment by casoncobi** [comment]
Also you may need to remove the '\n' at the end of CNAME file in the repo, just as you did here:

https://github.com/bromite/bromite.github.io/commit/097794f187916653be3f393cade1eb154f5fe3c7#diff-adc4bfdb0829dae99e3699393e3fbaa4

**Comment by csagan5** [comment]
> After you've updated DNS records (LGTM), you need to

Yes, I had tried this but it didn't work. I think it's related to the main domain Github pages.

> Workaround - use HTTP instead of HTTPS for repo URL.

Yes, I noticed earlier but did not have time until now to fix this.

> Also you may need to remove the '\n' at the end of CNAME file in the repo, just as you did here:

I just fixed this, thanks - although I find it a bit odd to be necessary.

**Comment by csagan5** [comment]
> Is this a known issue? It's not working for at least 2 days as far as I can tell.

The first day it was due to the historical hosting provider, then the day after I decided to switch to a CDN (Github pages) but could not get it fixed properly.

**Comment by dwinnert** [comment]
Just a quick question. Will the F-Droid repo update Bromite that was downloaded from your site? 

And changing https to http fixed it for me.

**Comment by csagan5** [comment]
> Will the F-Droid repo update Bromite that was downloaded from your site?

If you mean the [official website](https://www.bromite.org), yes. It's always the same APK files.

> changing https to http fixed it for me.

It will stop working as soon as the correct HTTPS version starts working again; the F-Droid client doesn't support redirects, as far as I know.

**Comment by dwinnert** [comment]
Ahh....Thanks!

and thanks for all your hard work!

**Comment by csagan5** [comment]
The issues should all be addressed now and the repository should work again as it was before problems arose.

**Comment by SimonBrazell** [comment]
Just tried switching back to HTTPS, it's still failing for me, might need a bit of time perhaps?

**Comment by csagan5** [comment]
> Just tried switching back to HTTPS, it's still failing for me, might need a bit of time perhaps?

No, it is completely rolled out as far as I can see: https://www.whatsmydns.net/#CNAME/fdroid.bromite.org

But apps/devices/DNSes might have their own caches that hopefully will respect the DNS entries TTLs.

**Comment by SimonBrazell** [comment]
No worries, I'll give it a few hours, try again and let you know the results.

**Comment by marcoismobile** [comment]
No problems here anymore, everything is working as before :) tnx!

**Comment by csagan5** [comment]
Yes, it seems working with the new solution on GitHub Pages.

**Comment by SimonBrazell** [comment]
Yes sorry got busy after I said I'd check again, its working now, thank you very much :-)
