### ISSUE TITLE
Error installing bromite browser update, f-droid, failed to verify

### ISSUE THREAD

**Issue by ithink314** [bromite/bromite#412]
Related #344 #241 #126 
### Bromite version

Version: from `78.0.3904.72 going to ...93`
Arch: `arm` 
Android version: `9.0`
Device model: shamu, motorola nexus 6

### Is this bug about the SystemWebView?
No

No support for SystemWebView installations is provided. 
OK

### Is the bug reproducible with latest version?
Yes
Do not report bugs which are not reproducible with latest version
OK
### Can the bug be reproduced with corresponding Chromium version?
I don't use it, but I doubt it.
Please pick the same version of Chromium as Bromite from here: https://github.com/bromite/chromium/releases
If the bug is reproducible then it might be a configuration issue or an upstream bug. Upstream bugs can be reported on the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) and do not forget to read [Chromium project bug reporting guidelines](https://www.chromium.org/for-testers/bug-reporting-guidelines) first.

### Is the bug a crash?
No? A fail to install update.

but logcat excerpt with greps of fdroid f-droid and bromite is attached.

### Describe the bug

After downloading update with f-droid, an error popup displays with failed to verify (see attached screenshot).

### Steps to reproduce the bug

1. Go to f-droid app, do steps to update to latest bromite
2. Watch it download and try to install
3. See error

### Expected behavior

Successful install of update

### Screenshots

[logcaty.txt](https://github.com/bromite/bromite/files/3835824/logcaty.txt)
![Screenshot_20191112-045903_F-Droidx](https://user-images.githubusercontent.com/843769/68667430-dd2bca80-053d-11ea-95ad-a48ecee6c034.png)
![Screenshot_20191112-050433_F-Droidx](https://user-images.githubusercontent.com/843769/68667431-ddc46100-053d-11ea-851a-4db2e5ce623c.png)
![Screenshot_20191112-051040_F-Droidx](https://user-images.githubusercontent.com/843769/68667433-ddc46100-053d-11ea-940f-212756fd18f6.png)

**Comment by csagan5** [comment]
@ithink314 is the issue resolved now?

**Comment by ithink314** [comment]
@csagan5 No, I also cleared cache for f-droid, and rebooted. Still seeing same behavior when trying update of bromite browser.

**Comment by ithink314** [comment]
Note: I also use Lineage 16 without Gapps.

**Comment by java-py-c-cpp-js** [comment]
@csagan5 No, the issue isn't resolved.

**Comment by csagan5** [comment]
It should be resolved now.

**Comment by java-py-c-cpp-js** [comment]
Now it works! Thank you very much for solving this error! :-)

**Comment by ithink314** [comment]
Also updated OK for me too. Thanks!
