### ISSUE TITLE
Some ads don't get blocked

### ISSUE THREAD

**Issue by peta9** [bromite/bromite#423]
### Bromite version

Version: `78.0.3904.93`
Arch: `arm`
Android version: `9.0`
Device model: Nokia 1

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

Feature not available in chromium

### Is the bug a crash?

No

### Steps to reproduce the bug

1. Go to this website: https://gamefaqs.gamespot.com/boards/942059-silent-hill-homecoming/45805581
2. Scroll down the webpage
3. See ads

### Expected behavior

No ads were expected

### Screenshots

![Screenshot_20191128-023645](https://user-images.githubusercontent.com/44788763/69760091-a1257600-1189-11ea-852f-fd285ca0fc27.png)
![Screenshot_20191128-023658](https://user-images.githubusercontent.com/44788763/69760117-aaaede00-1189-11ea-817f-631b2358aeab.png)

**Comment by csagan5** [comment]
Cannot reproduce this issue.

**Comment by csagan5** [comment]
@peta9 please see if you can provide other examples where this happens.

**Comment by peta9** [comment]
Unfortunately, I haven't come across any other such website yet. More tips to effectively reproduce the issue: 1) wait for a second or two after the site fully loads 2) now see, an AD card should appear after the very first comment (by a user on that site named LunarDream22)

**Comment by peta9** [comment]
P. S. It's a doubleclick ad by google

**Comment by csagan5** [comment]
I can see the doubleclick button showing; perhaps the filters have some option which is not handled by Chromium subresource filter.

@peta9 see if latest version of the filters are more effective?

**Comment by csagan5** [comment]
@peta9 @karma2424 check these two websites with latest version?

**Comment by Karma2424** [comment]
@csagan5 i already checked out the latest version but the problem still persist

**Comment by Karma2424** [comment]
@csagan5 my problem is that adblock is even blocking the whole chapter with ads when only it should be blocking ads

**Comment by peta9** [comment]
> @peta9 @Karma2424 check these two websites with latest version?

Nope, the problem still persists in the latest version (`78.0.3904.119`)

**Comment by csagan5** [comment]
@peta9 have you tested with https://kissmanga.com/Manga/Solo-Leveling/Chapter-095?id=569993 ?
Where did you download Bromite from?

@Karma2424 have you tested with https://gamefaqs.gamespot.com/boards/942059-silent-hill-homecoming/45805581 ?
Where did you download Bromite from?

**Comment by csagan5** [comment]
@peta9 for your issue I can release a fix but you should consider submitting an issue upstream: https://github.com/easylist/easylist

@Karma2424 in your case I am afraid there's nothing to be done, the website is broken without ads

**Comment by Karma2424** [comment]
@csagan5 just checked out https://gamefaqs.gamespot.com/boards/942059-silent-hill-homecoming/45805581 and it showing ads 
![Screenshot_20191203-020435_Bromite](https://user-images.githubusercontent.com/58363516/69993712-626d3280-1572-11ea-8ef6-08797d286089.jpg)

**Comment by Karma2424** [comment]
@csagan5 this problem does not exist on my pc where i use chrome with ublock so i can say that the website does not break without ads

**Comment by peta9** [comment]
> @peta9 have you tested with https://kissmanga.com/Manga/Solo-Leveling/Chapter-095?id=569993 ?
> Where did you download Bromite from?
> 
> @Karma2424 have you tested with https://gamefaqs.gamespot.com/boards/942059-silent-hill-homecoming/45805581 ?
> Where did you download Bromite from?

Yes, I can confirm that the adblock gets broken in the website https://kissmanga.com/Manga/Solo-Leveling/Chapter-095?id=569993 as mentioned by @Karma2424 

Probably the incorporated adblock script is not compatible with mobile devices? It's just a guess btw. Although, I recently used kiwi browser too with ublock origin to test this particular bug and I can confirm that those websites loaded as expected with no issues.

**Comment by peta9** [comment]
I've downloaded the compiled bromite apk from here https://github.com/bromite/bromite/releases/download/78.0.3904.119/arm_ChromePublic.apk

**Comment by csagan5** [comment]
> So, it shouldn't be a issue related to _Easylist_.

@peta9 @Karma2424 can you identify which filter blocks the `pagead2.googlesyndication.com` URLs? That is the one not blocked on the gamefaqs website.

On the other website the issue is different as the javascript simply results broken after blocking.

**Comment by peta9** [comment]
> > So, it shouldn't be a issue related to _Easylist_.
> 
> @peta9 @Karma2424 can you identify which filter blocks the `pagead2.googlesyndication.com` URLs? That is the one not blocked on the gamefaqs website.
> 
> On the other website the issue is different as the javascript simply results broken after blocking.

`Peter Lowe’s Ad and tracking server list`
Here's the screenshot of ublock origin blocking that ad link on kiwi browser
![Screenshot_20191203-171626](https://user-images.githubusercontent.com/44788763/70048661-dbab6a80-15f0-11ea-8601-ac0730aea108.png)

**Comment by csagan5** [comment]
@peta9 great, thanks - I will add it on next release

**Comment by csagan5** [comment]
@peta9 this should now be fixed in release `78.0.3904.130`

**Comment by peta9** [comment]
The banner ad on this site https://gamefaqs.gamespot.com/boards/942059-silent-hill-homecoming/45805581 still doesn't get blocked in the latest version (`78.0.3904.130`) of Bromite.

P. S.
1. Uninstalled the older version and made a fresh installation of the latest one
2. Changed nothing in the settings and opened the website

**Comment by csagan5** [comment]
> still shows the JavaScript bug

As I wrote before, this is not something that can be fixed.

> 1. Uninstalled the older version and made a fresh installation of the latest one

This is unnecessary; the filters are downloaded and updated separately.

**Comment by csagan5** [comment]
@peta9 looks like the Peter Lowe's list removed that rule, that's why it was not blocked in latest version. I have added a custom rule for it but we might have to remove it because upstream must have valid reasons to not have included it currently.

**Comment by peta9** [comment]
This issue still persists on my device, The Bromite version is 81.0.4044.97. It could compromise the browser privacy. You @csagan5 might want it to verify yourself?

**Comment by peta9** [comment]
P. S. I uninstalled the browser of the older version and clean installed the current one.

**Comment by csagan5** [comment]
> This issue still persists on my device

Which issue? I cannot reproduce the one on GameFaqs. For the other one if it still persists there's nothing to be done in Bromite.

> It could compromise the browser privacy.

As any new ad not (yet) covered by the filters.

**Comment by peta9** [comment]
> Which issue?

Google Doubleclick ad card.

> I cannot reproduce the one on GameFaqs.

Weird, it happens on the browser on my device though.

![Screenshot_20200412-214553](https://user-images.githubusercontent.com/44788763/79074025-9b2ecc80-7d07-11ea-9a08-5ca574007df8.png)
![Screenshot_20200412-214601](https://user-images.githubusercontent.com/44788763/79074035-a550cb00-7d07-11ea-8fd0-1e6124e7d1a0.png)

**Comment by csagan5** [comment]
> Weird, it happens on the browser on my device though.

Maybe you have outdated filters; see https://github.com/bromite/bromite/wiki/AdBlocking#update-mechanism

**Comment by peta9** [comment]
Sorry, I don't use PC, so can't use adb. But I can confirm that these are `location specific ads (or the filter installed in bromide itself is location specific)` and the bromite filter cannot block them for some reasons. When I use vpn and hide my location, the bromite filter seamlessly blocks the ads in the gamefaq website.

**Comment by randomshell** [comment]
I can't reproduce it on GameFAQs either.

@peta9 you can use Adguard DNS in the DoH settings as an alternative.

**Comment by peta9** [comment]
> I can't reproduce it on GameFAQs either.
> 
> @peta9 you can use Adguard DNS in the DoH settings as an alternative.

Yay, it works! Thanks for helping me out 😘

**Comment by mb555444** [comment]
I installed the 64bit version on my device, previously I used the 32bit version (both v81.0.4044.127). In the 64bit version, ads don't get blocked on some pages, e.g. slashdot.org or sonyalpharumors.com. Ads were blocked properly with the 32bit version.
