### ISSUE TITLE
Exit button visibility

### ISSUE THREAD

**Issue by pilsnerbeer** [bromite/bromite#619]
### Is your feature request related to privacy?
yes

es then provide URL and license information. -->

### Describe the solution you would like
I exit bromite regularly to clear data (cookies etc), however the "Exit" button is only visible when a tab is open, not from default view (picture). My suggestion is to show this "exit" button on said view so users dont have to open a new tab everytime in order to exit the browser.

![Screenshot_1](https://user-images.githubusercontent.com/36133540/84276737-f2e48b00-ab32-11ea-9d61-9d0b0621412b.png)

**Comment by csagan5** [comment]
Fixed in `84.0.4147.106`.

**Comment by pilsnerbeer** [comment]
It appears the issue is not quite fixed - the exit button is now there, but has no function when pressed.

**Comment by csagan5** [comment]
@pilsnerbeer I cannot reproduce this problem. Please open a separate bug report with steps to reproduce it.
