### ISSUE TITLE
DNS over HTTPS can't be enabled because of "managed browser"

### ISSUE THREAD

**Issue by CyberTeaTime** [bromite/bromite#832]
### Bromite version

Version: `83.0...`
Arch: `arm` or `arm64` or `x86`
Android version: (example: `9.0`)
Device model: (example: `SM-G960UZKABST`)

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes.

### Can the bug be reproduced with corresponding Chromium version?
Yes

### Is the bug a crash?
No.

### Describe the bug
On my private Android phone, I want to use secure DNS in Bromite. But it tells me that 'This setting is disabled on managed browser'.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to 'Menu/Settings/Privacy/Use secure DNS'
2. Click on 'toggle button'
3. It is gray and disallowed to click.
4. See error 'This setting is disabled on managed browser'.

### Expected behavior
When I click that switch button, the secure DNS function should be enabled.

### Screenshots
![Screenshot_20201202-213825.jpg](https://user-images.githubusercontent.com/64713045/100875883-f22d2000-34e9-11eb-8032-be17885ec6f6.jpg)

**Comment by csagan5** [comment]
> ### Can the bug be reproduced with corresponding Chromium version?
> Yes

Please report it on the Chromium issue tracker; it is not a Bromite issue.

**Comment by CyberTeaTime** [comment]
But not all Chromium-based browsers do this, such as Edge and Vivaldi.

Carl <notifications@github.com> 于 2020年12月7日周一 08:47写道：

**Comment by csagan5** [comment]
Let's see if it is possible to fix it.

**Comment by csagan5** [comment]
Fixed in `88.0.4324.95`.

**Comment by Fei1Yang** [comment]
This issue is not fixed, and with the new release, I'm even not able to change the DoH server for Bromite in work profile using Google's [Test DPC](https://github.com/googlesamples/android-testdpc) like the previous versions. instead, it always shows 'This setting is disabled on managed browser' and nothing applied.

**Comment by uazo** [comment]
I can't reproduce it, but @csagan5 maybe we have to change this 

https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/net/secure_dns_policy_handler.cc;l=29;drc=0b0661a20fa604ad87368572cd1e513b7e2abdd4

even if the code refers to "parental control software", do you think it is appropriate to allow it in those circumstances?

**Comment by csagan5** [comment]
@uazo I prepared a fix before reading your message; if "managed mode" is conflated with "parental control", then we will get rid of both. If one can have the latter (with the parent user in full control) without the former, then we can allow it.

I am not well versed on the parental control and Chrome user profiles functionality on Android.

**Comment by csagan5** [comment]
Fixed in `88.0.4324.141`.

@CyberTeaTime can you please test?

**Comment by Fei1Yang** [comment]
It's still partially works, I can only turn this option on but I'm unable to change DoH server provider.
(I have cleared managed configurations on the Test DPC app.)
![IMG_20210131_201859](https://user-images.githubusercontent.com/48410544/106383537-277fae00-6373-11eb-88ee-961e8f038b13.jpg)

**Comment by CyberTeaTime** [comment]
> Fixed in `88.0.4324.141`.
> 
> @CyberTeaTime can you please test?

Yes.  I have tested it. Although the button can be turned on now, but after returning to the previous level and re-entering the setting, the button is still off, and the settings below are still unavailable.
![Screenshot_20210201-064248.jpg](https://user-images.githubusercontent.com/64713045/106400366-61c77900-6461-11eb-9f5b-39b22f060c66.jpg)
![Screenshot_20210201-064305.jpg](https://user-images.githubusercontent.com/64713045/106400370-68ee8700-6461-11eb-8788-b5a5ec2b03fe.jpg)

**Comment by uazo** [comment]
we have to try https://github.com/bromite/bromite/issues/832#issuecomment-770251852 with `return false`

**Comment by csagan5** [comment]
@uazo yes you are right that seems to be able to fix the issue; I will add it to the [current patch](https://github.com/bromite/bromite/blob/88.0.4324.141/build/patches/Ignore-managed-state-for-secure-DNS.patch), assuming that what is there is still needed (based on these tests).

**Comment by Fei1Yang** [comment]
It's still unfixed, the behavior is the same as in the perivous verison.

**Comment by csagan5** [comment]
@uazo to continue on this we need to be able to reproduce the issue in the emulator. Or drop the patch.

**Comment by uazo** [comment]
mah, there would also be this to verify

https://source.chromium.org/chromium/chromium/src/+/master:chrome/android/java/src/org/chromium/chrome/browser/policy/EnterpriseInfo.java;l=236;bpv=1;bpt=0

it should send the list of histograms (chrome://histograms) and the localstate (chrome://local-state): for this last, attention there are sensitive data. do we have a way not to make that information public?

**Comment by csagan5** [comment]
To test this we just need to enable restrictive policies on the emulator; or am I missing something?

**Comment by uazo** [comment]
> To test this we just need to enable restrictive policies on the emulator; or am I missing something?

I tried with the multi-user, but I could not reproduce it.
Via chrome://histograms I think you could see what kind of policy is used

**Comment by Fei1Yang** [comment]
> I tried with the multi-user, but I could not reproduce it.

You could reproduce it by install [Test DPC](https://github.com/googlesamples/android-testdpc) to setup a new work profile and install bromite in it.

**Comment by uazo** [comment]
> You could reproduce it by install Test DPC 

yes, so I managed to reproduce it.
these are the values of the histograms, maybe we understand where the code is
```
Enterprise.UserCloudPolicyStore.LoadStatus = 1
EnterpriseCheck.IsFullyManaged2 = 0
EnterpriseCheck.IsManaged2 = 1
```

code seems here https://source.chromium.org/chromium/chromium/src/+/master:chrome/android/java/src/org/chromium/chrome/browser/policy/EnterpriseInfo.java;l=88 
i'll check.

**Comment by uazo** [comment]
@csagan5 I confirm that with simply changing `mSkipAsyncCheckForTesting = true` user can change that setting

```
diff --git a/chrome/android/java/src/org/chromium/chrome/browser/policy/EnterpriseInfo.java b/chrome/android/java/src/org/chromium/chrome/browser/policy/EnterpriseInfo.java
index 5af63ace81..fb8b72df99 100644
--- a/chrome/android/java/src/org/chromium/chrome/browser/policy/EnterpriseInfo.java
+++ b/chrome/android/java/src/org/chromium/chrome/browser/policy/EnterpriseInfo.java
@@ -43,7 +43,7 @@ public class EnterpriseInfo {
     private OwnedState mOwnedState;
     private Queue<Callback<OwnedState>> mCallbackList;

-    private boolean mSkipAsyncCheckForTesting;
+    private boolean mSkipAsyncCheckForTesting = true;

     /** A simple tuple to hold onto named fields about the state of ownership. */
     public static class OwnedState {

```

**Comment by csagan5** [comment]
@uazo ok, so you found the code responsible for this. 2 questions:
* the current patch we have in Bromite shall be fully dropped?
* is there a way to implement this without using a `ForTesting` variable?

**Comment by uazo** [comment]
> the current patch we have in Bromite shall be fully dropped?

I tried, it still works even without those, but I would keep those changes, they seem more than logical.
Reading here https://chromium-review.googlesource.com/c/chromium/src/+/1752931 looks like an experiment, probably sooner or later they will activate it.

> is there a way to implement this without using a ForTesting variable?

like this?

```
diff --git a/chrome/android/java/src/org/chromium/chrome/browser/policy/EnterpriseInfo.java b/chrome/android/java/src/org/chromium/chrome/browser/policy/EnterpriseInfo.java
index 5af63ace81..92c5e771da 100644
--- a/chrome/android/java/src/org/chromium/chrome/browser/policy/EnterpriseInfo.java
+++ b/chrome/android/java/src/org/chromium/chrome/browser/policy/EnterpriseInfo.java
@@ -81,11 +81,14 @@ public class EnterpriseInfo {
         sInstance = instance;
     }

+    public void getDeviceEnterpriseInfo(Callback<OwnedState> callback) {
+    }
+
     /**
      * Returns, via callback, whether the device has a device owner or a profile owner.
      */
     @SuppressWarnings("QueryPermissionsNeeded")
-    public void getDeviceEnterpriseInfo(Callback<OwnedState> callback) {
+    public void getDeviceEnterpriseInfo_NOCALL(Callback<OwnedState> callback) {
         // AsyncTask requires being called from UI thread.
         ThreadUtils.assertOnUiThread();
         assert callback != null;

```

**Comment by csagan5** [comment]
@uazo looks like your fix was incorporated here: https://github.com/ungoogled-software/ungoogled-chromium-android/commit/d2331cfb10b68f85a7350246f96f201597771791#diff-8f63ee312524c7728dc96ae6b209e7f7714641e1a8ebee48c59b6cd96a502590R51

**Comment by csagan5** [comment]
Fixed in `88.0.4324.187`.

**Comment by uazo** [comment]
caspita che occhio! (I don't know how it translates).
the problem, however, is as you say: if the variable `ForTesting` is removed, wiggle does not notice it and you lose the change.
I agree with you that the other solution is better.

**Comment by dksarangoung** [comment]
This issue is reproducing again in 104.0.5112.63.

**Comment by daankata** [comment]
I am also getting "This setting is disabled on managed browsers". Using latest version 107.0.5304.96.

**Comment by csagan5** [comment]
@daankata please open a new issue for that

**Comment by uazo** [comment]
@daankata please add also in the new issue a screenshot of `chrome://policy`

**Comment by gokulromanajay-cyber** [comment]
<img width="1080" height="2392" alt="Image" src="https://github.com/user-attachments/assets/8980ccc4-a283-4c73-8967-2332c8b3dd76" />

**Comment by gokulromanajay-cyber** [comment]
Please help
