### ISSUE TITLE
PAC URL option is reset to "direct" on Proxy Configuration settings

### ISSUE THREAD

**Issue by saintech** [bromite/bromite#908]
### Bromite version

Version: `88.0.4324.141`
Arch: `ARMv7`
Android version: `6.0.1`
Device model: `GT-N7000`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

N/A

### Is the bug a crash?

No

### Describe the bug

PAC URL option is reset to "direct" on Proxy Configuration settings.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to Settings -> Privacy -> Proxy configuration
2. Select 'Use PAC URL'
3. Enter usual PAC URL, for example https://antizapret.prostovpn.org/proxy.pac or https://raw.githubusercontent.com/anticensority/generated-pac-scripts/master/anticensority.pac
4. Click 'Apply'

### Expected behavior

Proxy settings are applied. PAC is used.

**Comment by csagan5** [comment]
Fixed in `88.0.4324.149`.

**Comment by ezellohar** [comment]
The bug is still present.
Version: 90.0.4430.59
Android version: 10
Device model: SM-960F

Is this bug about the SystemWebView?

No
Is the bug reproducible with latest version?

Yes
Can the bug be reproduced with corresponding Chromium version?

N/A
Is the bug a crash?

No
Describe the bug

PAC URL option is reset to "direct" on Proxy Configuration settings.
Steps to reproduce the bug

Steps to reproduce the bug:

    Go to Settings -> Privacy -> Proxy configuration
    Select 'Use PAC URL'
    Enter usual PAC URL, for example https://antizapret.prostovpn.org/proxy.pac or https://raw.githubusercontent.com/anticensority/generated-pac-scripts/master/anticensority.pac
    Click 'Apply'

Expected behavior

Proxy settings are applied. PAC is used.

Also, I'd like to add the following: the proxy is saved if, after having entered the PAC URL, you close the proxy setting window by clicking the X on the upper left corner.
Re-entering proxy setting will have the screen resetted, i. e.: no URL visible on the PAC URL bar, and the 'use system default' voice is selected.

**Comment by ezellohar** [comment]
The bug seems still present in 90.0.4430.59
