### ISSUE TITLE
Introduce hotkey Alt+D to focus address bar

### ISSUE THREAD

**Issue by Drugoy** [bromite/bromite#979]
Currently it supports Ctrl+L hotkey to do this action, but I prefer Alt+D, which is also a ~ universal standard.

**Comment by csagan5** [comment]
Fixed in `89.0.4389.92`.

**Comment by Drugoy** [comment]
@csagan5  90.0.4430.74 - Alt+D still doesn't focus location bar.

**Comment by csagan5** [comment]
The patch is there, but for some reason it does not work on Android.

**Comment by csagan5** [comment]
@uazo I have not figured out how to send a key combination via the emulator; I guess this has to be tested using a physical keyboard.

**Comment by uazo** [comment]
> I have not figured out how to send a key combination via the emulator

I found `adb shell input keyevent` or `adb shell sendevent`
https://developer.android.com/reference/android/view/KeyEvent.html

**Comment by csagan5** [comment]
> I found `adb shell input keyevent` or `adb shell sendevent`
> https://developer.android.com/reference/android/view/KeyEvent.html

These do not work with combinations, it is apparently impossible to send them via adb.

**Comment by uazo** [comment]
I've found the way.
you need to edit the emulator skin layout file, adding, by example
```
    buttons {
        ALT {
                image button.png
                x 1
                y 1
        }
    }
```
in the parts sections (like [layout.zip](https://github.com/bromite/bromite/files/7273179/layout.zip)).
so you have a button for the ALT key:
![image](https://user-images.githubusercontent.com/29201891/135750477-37702d0a-948a-4004-8095-7108ecf9a141.png)

at that point the ALT-D combination opens the search affectively:
![1](https://user-images.githubusercontent.com/29201891/135750645-9515de42-0194-4519-8793-7d6551d54452.gif)

**Comment by Drugoy** [comment]
@uazo no physical keyboard is seen
<img src="https://i.imgur.com/p0ESSoO.png">
<img src="https://i.imgur.com/RfLu6s2.png">

Tested on x86 version of Android (via QEMU) + latest Bromite - Alt+D there works okay.
